### ISSUE TITLE
Is there support for aarch64?

### ISSUE THREAD

**Issue by Nionor** [Frooodle/Stirling-PDF#115]
I'm running Ubuntu-20.04-aarch64 on Oracle Free Tier and when trying to start the container I get "exec /bin/sh: exec format error".
Am I doing something wrong or is it just not supported?

**Comment by Frooodle** [comment]
This functionality is being re-added today
It was dropped in a recent update by mistake and I was informed yesterday on discord 
Should be there by tomorrow

**Comment by Frooodle** [comment]
The 0.6.0-alpha should have arm64 support as a test already

**Comment by Nionor** [comment]
> The 0.6.0-alpha should have arm64 support as a test already

That one worked great! 
Thanks for the quick response and help!

**Comment by Frooodle** [comment]
Fixed for 'latest' tag as well now
