### ISSUE TITLE
[Feature Request] - Rest API

### ISSUE THREAD

**Issue by nodecentral** [Frooodle/Stirling-PDF#116]
Hi, 

I was just wondering if there were any plans to provide an API interface, where I can e.g. post a pdf and ask it to remove pages 2, 4 and 7 etc.

**Comment by Frooodle** [comment]
Will add full swagger API documentation next release

**Comment by Frooodle** [comment]
![image](https://user-images.githubusercontent.com/77850077/235138340-ed14d2c5-0c7f-403e-b54b-c7739fe9fb97.png)

**Comment by Frooodle** [comment]
https://app.swaggerhub.com/apis-docs/Frooodle/Stirling-PDF/1.0.0

**Comment by nodecentral** [comment]
Awesome, many thanks @Frooodle 

One quick question, (sorry if it’s obvious and I’m missing it) but when using the API, do I still provide the page numbers comma separated, and also where is the resulting pdf sent/stored ? Below is the curl command I’m testing, but I can’t tell if it worked as I can’t find the file created - see below..
````
[/share/Public] # cd /
[/] # curl -X 'POST' \
>   'http://192.168.102.134:8083/remove-pages?pagesToDelete=2%2C4' \
>   -H 'accept: */*' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'fileInput=@/share/Public/Escape_Fitness_Deck_2_0.pdf;type=application/pdf'
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
````
It feels like i need to provide a `fileoutput=@` location too, but Google wasn’t helping me much, so curious if you know ?.

**Comment by Frooodle** [comment]
The web ui directly sends to the api so same input output so yeah it would be comma separated etc

For curl stuff I've not tried it but for normal file output stuff you do 
Curl -o filename.pdf http://website

But not tested against my app
Lemme know how it goes

**Comment by nodecentral** [comment]
That was it, the addition of `-o` worked :-) …
````
[/share/Public] # cd /
[/] # curl -X 'POST' \
>   'http://192.168.102.134:8083/remove-pages?pagesToDelete=2%2C4' \
>   -H 'accept: */*' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'fileInput=@/share/Public/Escape_Fitness_Deck_2_0.pdf;type=application/pdf' \
>   -o '/share/Public/Escape_Fitness_Deck_2_0-NEW.pdf'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  684k  100  340k  100  343k  12.4M  12.5M --:--:-- --:--:-- --:--:-- 25.6M
````
