### ISSUE TITLE
[Feature Request] - Mapped Volume and Batch processing

### ISSUE THREAD

**Issue by nodecentral** [Frooodle/Stirling-PDF#117]
Hi

Just wondering if there was anything on the road map to support mapped volumes via docker, so there is always a default source, one that could also be used for batch processing. Do XYZ to all PDFs in /folder/.

**Comment by Frooodle** [comment]
No planned sorry, I am actually planning to move away from server side things as much as possible in first place to get it all UI side. (for basic functionality like removing pages)
Not many have the usecase of needing this type of file access
That being said the Current implementation does do parallel processing on all server side features currently. Only downside is right now there is no max thread count so i would be careful doing 100+

**Comment by nodecentral** [comment]
Thanks @Frooodle 

Apologies I realise I wrapped two requests into one :-)

if I could highlight a preference, being able to have a mapped volume would be nice, so that you can always have a default location come up in the UI, rather than always having to go off and search for the files.

Batch processing would be nice too, but to a degree it sounds like the API in my other request will help with that..

**Comment by Frooodle** [comment]
I don't have any plans to develop this but since the api will be public and its threadsafe you can create your own scripts for this I guess
