### ISSUE TITLE
[Feature request] markdown to pdf conversion

### ISSUE THREAD

**Issue by MeGilles** [Frooodle/Stirling-PDF#124]
It would be nice to be able to convert markdown files to pdf, leveraging the formatting capabilities.
As a example, the node package markdown-pdf [1] first converts markdown to HTML and then render it in a PDF.

[1] : https://github.com/alanshaw/markdown-pdf

**Comment by thelazyoxymoron** [comment]
Would love to get this. Currently using [md2pdf](https://github.com/realdennis/md2pdf), but getting it integrated under s-pdf umbrella would be much preferred.
