### ISSUE TITLE
[Bug] Detect/Split Scanned photos needs scripts under root /scripts

### ISSUE THREAD

**Issue by Thomas-Do** [Frooodle/Stirling-PDF#128]
"Detect/Split Scanned photos" searches for the script "split_photos.py" under root /scripts/ and not under the Stirling-PDF install folder ./scripts/. This may work in docker installations but needs to copy or symlink the scripts folder to / in standard installations.

**Comment by Frooodle** [comment]
Good point, will resolve next patch

**Comment by Frooodle** [comment]
Done as part of v0.8.0 release. which is now live
