### ISSUE TITLE
Compression does not always reduce the size of files??

### ISSUE THREAD

**Issue by NexusEFR** [Frooodle/Stirling-PDF#129]
I think that the pdf compression to reduce the size does not work correctly or not always with all types of pdf, possibly it is not able to reduce the quality of the images to 150dpi or similar. Is this failure possible or is it a limitation? I tried to compress to reduce the size of 3mb using any of the 3 options and all exports left the file size practically the same. But using PDF4me (API mode with app or automation) has been able to reduce it to 800kbs (web mode) and 1.5mbs (print mode). I include the pdf that you can try to try the compression. Thanks anyway, your project is very good, very useful and I love it!
[ATHLET_ES_low.pdf](https://github.com/Frooodle/Stirling-PDF/files/11382345/ATHLET_ES_low.pdf)

**Comment by Frooodle** [comment]
I'll take a look and maybe try some other compression methods 
Appreciate the example pdf 
Helps a lot

**Comment by Frooodle** [comment]
Should be fixed now

**Comment by NexusEFR** [comment]
Awesome! Thank you very much, I like your project more and more each time for all the new features you are introducing, but also because it maintains privacy with self-hosting. I'm commenting this here, but I don't know if someone has already mentioned or requested it, the possibility of restricting access to the web portal with a login, since even if it's for internal use, it could be used to connect it with a ddns and share it with colleagues. Thanks again, I hope to make a donation through my company.

**Comment by Frooodle** [comment]
I keep having so many requests for it though, you are probably like the 12th person.... but I don't see the logic of adding it to the app itself 
I am tempted to make a business version update with LDAP support and things...
But no focus on that for now, it's a good 3 months off
