### ISSUE TITLE
[Feature Request] - Ability to find and remove blank pages 

### ISSUE THREAD

**Issue by nodecentral** [Frooodle/Stirling-PDF#134]
Hi

As I scan a lot of documents in , there are often numerous blank pages. It would be great to have a facility where it can scan a pdf, find blank pages and then remove them..

**Comment by Frooodle** [comment]
@nodecentral  Can you define a blank page?
If its a page without text or images thats easy to detect and remove, if its a scanned paged as you mentioned the pdf page isnt blank but contains a image of pure white..
I can use computer vision to detect this but then there are also the usecases or blank pages that are different colours and with lines but no text etc..
Can you try expand the definition slightly to help clarify things

**Comment by Frooodle** [comment]
Like would a blank page still be a blank page if it has a footer but nothing else?

**Comment by nodecentral** [comment]
> Like would a blank page still be a blank page if it has a footer but nothing else?

Is the footer you are referring to something visible on the page, or something hidden in the pdf itself ?

In my situation the blank pages occur due to scanning documents in and it thinking the back of a page (empty page) is a page to keep..

**Comment by Frooodle** [comment]
Cool ill develop the app to handle blank pages added in software (no text or images) 

And blank pages caused by scanning, since it's giant image I will try detect the image contains no information by checking each pixel 
Can't be sure it will always work due to see-through paper or dust etc but I'll see what I can do 
Also for ease I'll do white only paper

**Comment by nodecentral** [comment]
Many thanks @Frooodle 

>, since it's giant image I will try detect the image contains no information by checking each pixel Can't be sure it will always work due to see-through paper or dust etc but I'll see what I can do Also for ease I'll do white only paper

I seem to recall seeing it done elsewhere, I think they used a % / tolerance level on what’s found, or maybe it was a colour range, sorry can’t be sure, maybe a combination of them both..:-)

**Comment by Frooodle** [comment]
Done as part of v0.8.0 release. which is now live

**Comment by Frooodle** [comment]
This is first interaction so i imagine it will have some issues... i added some logging as well
Please let me know how it goes, it might need improvements down the line
