### ISSUE TITLE
[Feature request] Ability to personnalize URI

### ISSUE THREAD

**Issue by MayannF** [Frooodle/Stirling-PDF#136]
Hi,

I would like to suggest a simple feature making possible to expose s-pdf behind a reverse proxy using subfolders.

I managed to make this work on a test container by simply adding 
`server.servlet.context-path=${CONTEXT_PATH:/}`  to application.properties. 
With this, if I run the container with option -e CONTEXT_PATH=/s-pdf, the webapp is fully accessible from mydomain.com/s-pdf

If no option is passed, it keeps the default root path /. 

I'm very new to git so I hope this is an appropriate contribution !

**Comment by Frooodle** [comment]
Awesome idea, thanks ill add this for next release, or if you want you can raise a PR

**Comment by MayannF** [comment]
So glad you like the idea!

As said, I'm very new to git, but I'll try to make the PR tomorrow.

Btw huge thanks for the project, it's really amazing

**Comment by Frooodle** [comment]
Done as part of v0.8.0 release. which is now live
