### ISSUE TITLE
[Bug] Image To PDF não mantém proporção das imagens

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#140]
Ao converter varias imagens ou apenas uma imagem para PDF, a imagem gira e fica esticada, ou seja, não mantem a mesma proporção no arquivo PDF, mesmo marcando a caixa "Girar PDF automaticamente". Segue as imagens para conferencia e os arquivos gerados.

IMAGENS UTILIZADAS:
![IMAGEM_1](https://github.com/Frooodle/Stirling-PDF/assets/48888772/986a3733-58c3-44af-887a-e35dfe91de9d)
![IMAGEM_2](https://github.com/Frooodle/Stirling-PDF/assets/48888772/9080410c-16fd-403d-bff9-beb3059a3a0d)
![IMAGEM_3](https://github.com/Frooodle/Stirling-PDF/assets/48888772/ef2121e8-b41f-411a-a1ac-20a93eec98bc)
![IMAGEM_4](https://github.com/Frooodle/Stirling-PDF/assets/48888772/b0c54217-d699-4220-8211-0fdeb771ab6c)

ARQUIVO GERADO:

[IMAGEM_1_coverted.pdf](https://github.com/Frooodle/Stirling-PDF/files/11444429/IMAGEM_1_coverted.pdf)

Isso pode ser corrigido no codigo?
 Obrigado!

**Comment by JefPresotto** [comment]
Outra questão relacionada ao arquivo PDF é que ele não sai no formato A4.

**Comment by JefPresotto** [comment]
obrigado!   :)

**Comment by Frooodle** [comment]
Fixed for next release this weekend :)
