### ISSUE TITLE
[Bug] Multipage TIFF = single page PDF

### ISSUE THREAD

**Issue by gittynick** [Frooodle/Stirling-PDF#142]
With a multipage TIFF, whether i try "File to PDF" or "image to PDF", it seems that Stirling-PDF only converts the first page
It would be nice to convert a multipage TIFF into either a multipage PDF or in several single PDFs
(it is possible for example via Tifflib)

BTW, it would also be cool to add an option to convert a colour TIFF to a greyscal PDF 😉 

Keep the good work 👍

**Comment by Frooodle** [comment]
File to PDF uses LibreOffice API so i cant change that functionality 
For image to PDF I can look into adding this though ill take a look :)

**Comment by Frooodle** [comment]
Just fixed TIFF and added colour option for next release :)
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/0ce064ac-3878-4c72-9066-97bae14184d1)

**Comment by gittynick** [comment]
Wow: that was an impressively fast reaction!  🥇 
Thanks

**Comment by Frooodle** [comment]
Done as part of v0.8.0 release. which is now live
