### ISSUE TITLE
Application Logo 

### ISSUE THREAD

**Issue by mms-gianni** [Frooodle/Stirling-PDF#15]
Hey

I like your project a lot and I want to add it to the service list in [Kubero](https://github.com/kubero-dev/kubero). This will allow users an easy installation on a Kubernetes cluster. But I need a (more or less) square icon/logo . 

![image](https://user-images.githubusercontent.com/2052196/215774105-1706d6af-4495-4b88-ae9f-687a8d699eb7.png)

**Comment by Frooodle** [comment]
There is a reason my logo is just the words PDF, I am not good at logo graphical design
If anyone wants to submit what they think would be a cool logo that would be awesome and id adopt that into the app
Otherwise, until then we are stuck with
https://github.com/Frooodle/Stirling-PDF/blob/main/src/main/resources/static/favicon.svg

**Comment by Frooodle** [comment]
@mms-gianni  hey that looks good! can you see if it can have something similar but document related?
Like same logo but in the shape of a file/PDF not a circle maybe?

**Comment by mms-gianni** [comment]
Midnightjourneys output is often pretty random when it creates simple logo's 

This prompt was: "A simple and flat logo, shaped as a document with an "S" on it, vectors, 2 colors"
![image](https://user-images.githubusercontent.com/2052196/215882014-a5522d24-2b33-4945-bf2a-e633f20a06d3.png)

![image](https://user-images.githubusercontent.com/2052196/215885691-d94b0097-381d-40da-9391-3bafadd72489.png)

**Comment by Frooodle** [comment]
Been messing around with this wanting white/red colors so it looks PDF related
and with a S in...
So far got 
![File icon with a S in the middle as a flat modern logo consisting primarily of the color red and white](https://user-images.githubusercontent.com/77850077/216144896-b435cc80-90d5-4ff8-903c-72ef2c09d769.png)

But this looks almost TOO file-ish

**Comment by Frooodle** [comment]
> I fully understand that 😄
> 
> Here is what Midjourney came up with "a simple flat logo with an 's', modern"
> 
> ![image](https://user-images.githubusercontent.com/2052196/215799053-8f9087c2-0fec-4c7a-9039-09df0a67bd48.png)

I am slowly growing to like this more and more as time passes

**Comment by mms-gianni** [comment]
I could not resist and asked MJ one more time. And this generated logo is awesome, but it would need some tweeks. 

The downside is: it does not work very well on a black background. 

![image](https://user-images.githubusercontent.com/2052196/216169925-1c83b5bb-d281-44ab-8487-682dd5a985bf.png)

**Comment by Frooodle** [comment]
Sounds good to me!

**Comment by mms-gianni** [comment]
Ok ... got it as svg. Had to repaint it and fixed some AI Glitsches. 
I got also the inkscape file with all separated layers a, PNG and webready svg. 
 
 
So you want me to make a PR?

![image](https://user-images.githubusercontent.com/2052196/216726391-fc5a0859-a638-4c41-ac44-74ccf1c65170.png)

**Comment by Frooodle** [comment]
yeah please and accept it and we can go forward as this as logo

**Comment by Frooodle** [comment]
thanks! looks awesome

**Comment by Frooodle** [comment]
Cool merged PR.
Will change logo to this tomorrow various places 
Thanks for your help on this

**Comment by mms-gianni** [comment]
You're welcome. 😄

**Comment by Frooodle** [comment]
Thanks, added to favicon and readme, well add elsewhere as part of larger UI updates
