### ISSUE TITLE
Error when not running as root

### ISSUE THREAD

**Issue by quentinus95** [Frooodle/Stirling-PDF#157]
Hello,

As this application handles a lot of user input, I want to run it as non-root (e.g., UID 2000).

When doing so, some functions work (e.g., signature or turning image(s) to PDF), but some others such as PDF to Word bring the following issue:

```
unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly.\nLibreOffice 7.0 - Fatal Error: The application cannot be started. \nUser installation could not be completed. 
```

Can we use /tmp instead?

Thanks!

**Comment by Frooodle** [comment]
This isnt the path Stirling-PDF uses but instead the path libreOffice is using which is what is used for the conversions, I assume there is some LibreOffice configuration to change this path

**Comment by Frooodle** [comment]
@quentinus95  did you ever find a fix for this your side?

**Comment by quentinus95** [comment]
@Frooodle no I did not have time to investigate (yet), no workaround, I just do not use the feature for now.

**Comment by quentinus95** [comment]
@Frooodle correcting the title as I am running this with Docker.

Starting with Stirling 0.13 I'm getting the following error:

> Caused by: java.nio.file.AccessDeniedException: /configs

Very easy to reproduce:

> docker run -it --user 2000 frooodle/s-pdf:0.13.1

Gives the error.

Running with a UID >= 2000 is considered as a best practice (even more for a project such as this one where you handle untrusted input).

**Comment by Frooodle** [comment]
Sorry this issue got lost among others 
I am adding support for this under
https://github.com/Frooodle/Stirling-PDF/issues/332

as part of next update

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/releases/tag/v0.14.0
done!
