### ISSUE TITLE
Where to put custom setup scripts?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [Frooodle/Stirling-PDF#159]
I have some scripts in mind:

- Full native setup, Debian based and Fedora
- Setup in Distrobox and Toolbox (I will test which box consumes least resources)
- Modification to work with Libreoffice Flatpak

Should there be an extra folder for these?

**Comment by Frooodle** [comment]
first two extra custom script folder is fine as long as well named

3rd im not sure what entails with Libreoffice Flatpak changes as never used it
Libreoffice is used by the unoconv application. if its purely changing how its installed not how its called etc then yeah that can go in same custom-install-scripts folder or whatever you think would be a good name

**Comment by Frooodle** [comment]
Assumed ticket closed?
