### ISSUE TITLE
[Feature Request] Compression with Ghostscript

### ISSUE THREAD

**Issue by thmmsn** [Frooodle/Stirling-PDF#163]
Right now, Stirling PDF uses ocrmypdf as its compression algorithm. But to make Sterling PDF even better, it could also add Ghostscript as an option for compressing PDF files.

**Comment by Frooodle** [comment]
I actually think ocr my pdf using ghostscript in background 

I'm actually planning on changing this to use ghostscript directly as some people have seen issues

**Comment by Frooodle** [comment]
Done!
