### ISSUE TITLE
[Feature Request] Drag and drop files

### ISSUE THREAD

**Issue by thmmsn** [Frooodle/Stirling-PDF#164]
As title says. 

If drag and drop to main screen; then deactivate/remove/filter out tools not working with single or multiple files.

**Comment by Frooodle** [comment]
Pretty much all of the processes work with multiple files as for add password for instance you can add same password to 20 files at once etc

Only ones that don't are UI only features like compare and sign.. and that's about it

I don't really see benefit of this filter

**Comment by thmmsn** [comment]
Ok
