### ISSUE TITLE
Feature: watchdir and OCR

### ISSUE THREAD

**Issue by poudenes** [Frooodle/Stirling-PDF#167]
Hi All,

What a great tool !!!! Would be nice to see following feature in near future:

1) watch folder to add pdf files that automate get OCR and write pdf back to other folder. Manual select what folder to watch and store new file

2) Watch folder for images to convert them automatic to a PDF file and save this to a different folder.

**Comment by Frooodle** [comment]
duplicate of
https://github.com/Frooodle/Stirling-PDF/issues/138

However yes this is planned! but not eta
