### ISSUE TITLE
Feature : Enable/Disable for single functions

### ISSUE THREAD

**Issue by SICUFI** [Frooodle/Stirling-PDF#169]
Hello,

thanks for this awesome self-host app.

We are providing this to our users and it works flawlessly, just a little feature request that could help.

Would it be possible to enable/disable the offered features on deploy? 
Maybe trough Env variables.

There are many features offered but we only use some of them and we would like to simplify the interface as much as possible!

Thank you :)

**Comment by Frooodle** [comment]
I am thinking of adding this functionality for a lightweight version of stirling pdf so can try bundle this change with that

Will let you know

No eta though

**Comment by Frooodle** [comment]
Although in meantime i recommend the favouriting feature which might help some confusion

**Comment by SICUFI** [comment]
Will suggest this in the meantime, thank you!

**Comment by Frooodle** [comment]
Added in this release!
let me know how it goes

Disable and remove endpoints and functionality from Stirling-PDF. Currently the endpoints ENDPOINTS_TO_REMOVE and GROUPS_TO_REMOVE can include comma seperated lists of endpoints and groups to disable as example ENDPOINTS_TO_REMOVE=img-to-pdf,remove-pages would disable both image to pdf and remove pages, GROUPS_TO_REMOVE=LibreOffice Would disable all things that use LibreOffice. You can see a list of all endpoints and groups [here](https://github.com/Frooodle/Stirling-PDF/blob/main/Groups.md)

**Comment by Frooodle** [comment]
Please let me know if this works for you okay or if you have issues as per my knowledge you would be only one using this feature currently

**Comment by SICUFI** [comment]
Seems to be working flawlessly!

Thank you very much, such a speedy implementation :D

**Comment by SICUFI** [comment]
Hello,

where can I find an updated groups.md with the endpoints name for the new technologies added? 
Thank you!

**Comment by Frooodle** [comment]
Ahh sorry i had forgot to update the documentation for the new feature I'll have that done soon

**Comment by Frooodle** [comment]
multi-page-layout , scale-pages     and  cert-sign added
