### ISSUE TITLE
Some functions are producing .htm files rather than .pdf

### ISSUE THREAD

**Issue by 2004gixxer600** [Frooodle/Stirling-PDF#170]
What is the reason for this?  Some of the functions are saving what should be a PDF as .htm thats unusable.

thx

**Comment by Frooodle** [comment]
can you please give examples?

**Comment by 2004gixxer600** [comment]
Compress function, add password, trying some more.  Used 2 browsers.  when converting PDF to word Doc, plain .doc is .htm but .docx seems to produce a PDF.

**Comment by Frooodle** [comment]
yeah i think its nginx related, it seems to work for others fine

**Comment by 2004gixxer600** [comment]
Yup! it was! For others having this issue behind Nginx, the default file upload size is 1MB, you need to add the following in your Nginx sites-available file. client_max_body_size SIZE;    Where "SIZE" is 50M for example for 50MB.

**Comment by Frooodle** [comment]
Thanks for providing the fix for others :)

**Comment by 2004gixxer600** [comment]
One quick question. Does this software retain the uploaded pdf’s or is it deleted immediately? As that’s a concern many people seem to have

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/discussions/174

Might be useful for you 

Basically nothing kept at all
