### ISSUE TITLE
[Feature Request] Add Text

### ISSUE THREAD

**Issue by sandivuk** [Frooodle/Stirling-PDF#172]
I know we can currently add text input via the Sign tool, but this text even when brought down to its smallest size is often too big to use for filling out forms. The current implementation could work if:

1) The text dragged onto the PDF can be made much smaller and
2) The text can be drag-resized while maintaining its x/y aspect ratio so as to not stretch the text accidentally

**Comment by Frooodle** [comment]
Yup I will add this!

**Comment by Frooodle** [comment]
Added this now will be next release, hold ctrl to maintain aspect ratio (bit jumpy at the moment but works)
and minium size is now 10 times smaller.
It does have issue with movement after making it smaller.
I am working on fix but might get moved into release after next for that
