### ISSUE TITLE
[Feature Request] Password protected site

### ISSUE THREAD

**Issue by poudenes** [Frooodle/Stirling-PDF#173]
Hi All,

I love this tool so much I created a subdomain so I can use it on work also if needed.
Would be nice to have the option to create a username/password to protect the site itself.

Now if someone finds out the subdomain they can use the tool also... :) haha

**Comment by yustmenl** [comment]
I did the same and i agree a paswword protection would be agreat adition.

**Comment by Frooodle** [comment]
I don't plan on adding authentication to this app since I think there are better alternatives by vetted 3rd parties 

I recommend you try secure it with those 
Even nginx which can add auth could be used instead

**Comment by poudenes** [comment]
Ok. Im using Cloudflare Zero Trust. And never see a option to password protect specific public hostnames.

**Comment by Frooodle** [comment]
This is now supported in latest release! v0.13.0

**Comment by thor9898** [comment]
> This is now supported in latest release! v0.13.0

Where?

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF#login-authentication
