### ISSUE TITLE
Are any pdfs retained in the server? 

### ISSUE THREAD

**Issue by 2004gixxer600** [Frooodle/Stirling-PDF#181]
Questioned a lot on this specific issue. I didn’t see anywhere in the documentation about this although I do believe nothing is stored permanently. Can anyone clarify? 

Thanks

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/discussions/174

Should be helpful for you
I will also update documentation to state this

**Comment by Frooodle** [comment]
added to readme.md
