### ISSUE TITLE
please add a login function to prevent unauthrized use

### ISSUE THREAD

**Issue by kevinwenyu** [Frooodle/Stirling-PDF#183]
i build a docker version on my NAS and internent accessble. but i dont want anyone else use it without authorzation. is there any function like login?

**Comment by Frooodle** [comment]
Please see https://github.com/Frooodle/Stirling-PDF/issues/32 and https://github.com/Frooodle/Stirling-PDF/issues/173
I will create a FAQ for this later but its not something i plan to add

**Comment by Frooodle** [comment]
Different auth methods are currently being discussed on my discord

**Comment by Frooodle** [comment]
This is now supported in latest release! v0.13.0
