### ISSUE TITLE
Wrong page order when opening several files at once with "PDF Multi Tool"

### ISSUE THREAD

**Issue by philipp-koch** [Frooodle/Stirling-PDF#190]
Using "PDF Multi Tool", when I click the "open file(s)" button and select more than one file, the documents' pages are getting "mixed up" (i.e. single pages from document 2 appear randomly between pages of document 1). This does not happen if I first open document 1 and then, as soon as document 1 is displayed, open another document (whose pages are then appended to the first document). I'm using app version 0.8.2.

**Comment by jordyjordy** [comment]
@Frooodle I think this Issue can be closed with the merging of PR #228 ?

**Comment by Frooodle** [comment]
Should be in latest release

**Comment by philipp-koch** [comment]
I can confirm that with 0.10.1 the issue is resolved: Pages are now in order even after selecting several files in the file open dialog. Thanks to both of you, @Frooodle and @jordyjordy, for solving this!
