### ISSUE TITLE
[Feature Request] Fake duplex sorting feature

### ISSUE THREAD

**Issue by tk4arts** [Frooodle/Stirling-PDF#209]
When using a non duplex ADF Scanner, it is only possible to scan duplex documents by manually scan every page into one document and turn every page after every scan.
The desired function would be to scan all front pages and then all back pages in the same document. Then this document should automatically be sorted that the pages are sorted correctly. 
Example: 
5 pages (10 sides, duplex)
1. Step scan 5 front pages
2. Step scan 5 back pages
3. Now Sorting is 1,3,5,7,9,10,8,6,4,2
4. Step Fake duplex sorting to Sort pages 1,2,3,4,5,6,7,8,9,10

**Comment by Frooodle** [comment]
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/1f838efc-7893-4cb2-9394-476c4091ab11)

**Comment by Frooodle** [comment]
Just finished making this, there will be dropdown option for custom modes in next release with pre-selected organisation

**Comment by tk4arts** [comment]
Hi,
Thanks for the quick integration. One question is it now implemented as in the screenshot? Because when you scan with a non duplex scanner you have first all the fronts and then all the backs, but the backs are in reversed order since the papers have been turned around.

so the sorting should not be:
1,n/2+1,2,…
Because then the sorting from my initial post would be: 1,10,3,8,…

It should rather be like in my second post:
1,n,2,n-1,…

I hope it is clear what I meant.

And thanks again for the great work!

**Comment by Frooodle** [comment]
Just made correction i see what you meant now, thanks for re-explaining

**Comment by Frooodle** [comment]
This should be live with alpha tag now will release later in week
