### ISSUE TITLE
Wrong formatting of file name when compressing multiple pdfs with ÅÄÖ and space?

### ISSUE THREAD

**Issue by thegreenmilecornant** [Frooodle/Stirling-PDF#210]
Hi!

First of all - thank you for a great selfhosted utility that I have started using daily! Really looking forward to the future update with the "Full custom logic pipelines to combine multiple operations together". Hoping I can batch OCR and compress PDF's in one go.

I have a small issue that prevents me from being 100% effective. The issue shows when compressing multiple PDF:s at the same time.

Let's take an example `Pål pdf.pdf`.

If I compress the pdf alone the new name would become `Pål pdf_compressed.pdf`. Perfect.
If I compress multiple PDF:s at the same time (regardless of downloading as archive or standalone) - the filename would become `P%C3%A5l%20pdf_Optimized.pdf`. Not so perfect.

It seems that ÅÄÖ and space results in some sort of "%XX%"-formatting error.

Can someone reproduce? Is  there something I can do to fix it on my end?

**Comment by Frooodle** [comment]
I see what issue is, I will try resolve this next patch :)

**Comment by Frooodle** [comment]
This should be fixed in latest alpha tag and will be included in main release when that happens
