### ISSUE TITLE
[Feature Request] N-Up / PDF Imposition

### ISSUE THREAD

**Issue by LaserKaspar** [Frooodle/Stirling-PDF#212]
# Description
It would be great if it were possible to condense multiple pages of a PDF to a single one of the output PDF.

## Better Visualisation:
https://superuser.com/questions/1712834/convert-a-single-page-pdf-to-double-page

## Options 1 (Sadly no option for me): 
Convert the pages to images, move them and convert it back to a PDF. All text information would be lost.

## Option 2:
Do it by changing the formatting of the pdf itself. Much harder, but much better.

# Tools that do this:
- https://pdfresizer.com/multipage (Option 2)
- https://deftpdf.com/de/n-up-pdf (Option 2)

# Possible Implementation (Option 2)
## PDFBox
- https://stackoverflow.com/questions/12093408/pdfbox-merge-2-portrait-pages-onto-a-single-side-by-side-landscape-page
- https://stackoverflow.com/questions/73800188/pdfbox-nup-pdf-document

## iText
- https://stackoverflow.com/questions/56627182/how-merge-and-rotate-two-pdf-pages-to-one-page-itext

Thanks for this great pice of software & the support on Discord (:

**Comment by Frooodle** [comment]
this is up now with the alpha tag, will release it later in week

**Comment by LaserKaspar** [comment]
This was insanely fast! Thanks a lot! Working prefectly. Only problem is that it renames every file on download, so I need to rename them back. Would be great if it kept the original filename and just appended "-modified". But I just N-up'ed a buch uf documents you saved me literal hours of work! Really appreciate it!

**Comment by Frooodle** [comment]
I'll fix naming , thanks for the feedback
