### ISSUE TITLE
[Sugestão de recurso] aumento do numero de DPI em PDF PARA IMAGEM

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#216]
Boa tarde, 
Ao utilizar alguns PDF que foram escaneados de documentos muito antigos, os dados estão muito ruins no PDF, e ao converter para imagem, o limite em DPI só vai até 100dpi e mesmo em 100dpi a qualidade fica muito baixa. Seria possivel aumentar a possibilidade de maiores taxas de DPI? até 600 por exemplo? 
Muitos destes documentos são mapas oficiais que foram confeccionados a décadas, e hoje estamos fazendo o arquivamento e criando documentos com base neles, por isso a necessidade de maiores resoluções nas saidas das imagens. Em algumas saidas, os desenhos e chanfros das plantas CAD (que foram digitalizadas através de uma plotter) ficaram quase imperceptiveis e em outros pontos, desapareceram.

**Comment by Frooodle** [comment]
I see my mistake will change for for next patch, will have no limit

**Comment by JefPresotto** [comment]
Obrigado!
