### ISSUE TITLE
[non docker] Permissões do Card Adicionar Senha não funcionam

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#219]
Boa tarde colega, 
Fiz vários testes com diferentes arquivos no card ADICIONAR SENHA e notei que as permissões não funcionam, nenhuma delas.
A senha que é definida é apenas SENHA DE ABERTURA, e não senha de permissão, talvez por isso as permissões não funcionem.

	*CONFIGURAÇÃO 1:...40 (RC4)/128(RC4)/256(AES) bits (SEM NENHUMA PERMISSÃO DEFINIDA, APENAS A SENHA DEFINIDA)....ok

	*CONFIGURAÇÃO 2:...40 (RC4)/128(RC4)/256(AES) bits (COM PERMISSÕES DEFINIDAS E SENHA DEFINIDA)....ERRO
	1-[X] Evitar a montagem do documento...............{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	2-[X] Impedir extração de conteúdo.................{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	3-[X] Impedir extração para acessibilidade.........{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	4-[X] Impedir o preenchimento do formulário........{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	5-[X] Impedir modificação..........................{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	6-[X] Impedir modificação de anotação..............{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	7-[X] Impedir impressão............................{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}
	8-[X] Impedir a impressão de formatos diferentes ..{40 bits = Não funciona}/{128 bits = Não funciona}/{256 bits = Não funciona}

Mesmo com as permissões definidas, acessei normalmente todas as permissões e efetuei as transações no pdf como se não tivessem sido definidas.

Grato pela atenção!
Att,
Jeferson Presotto

**Comment by Frooodle** [comment]
You're right i should have 2 passwords, one for owner which grants all, one for user which is limited by permissions set.
Will enhance this for next release, quick fix

**Comment by JefPresotto** [comment]
Muito obrigado pelo feedback, eu utilizo o modo convencional (grable) pois não sou muito bom com o docker, mas ja estou estudando isso!

Obrigado pelo trabalho que tem feito, tem ajudado muitas pessoas como eu!
