### ISSUE TITLE
[Feature Request] Split PDF split on pattern/blank page

### ISSUE THREAD

**Issue by SBCV-apegram** [Frooodle/Stirling-PDF#224]
Allow for splitting the PDF based on a pattern (eg. every 2 pages) or on blank pages.

**Comment by Frooodle** [comment]
should work now with the prompt 

2n

**Comment by SBCV-apegram** [comment]
What would the syntax for this be? '2n' is every two pages?

**Comment by Frooodle** [comment]
Correct 
Also supports things like 2n+1 etc or 3n-1
