### ISSUE TITLE
[non-docker] Sugestão de Recurso: Contador de acesso na pagina e nos cards para estatísticas.

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#226]
Bom dia, 
Alguns cards (serviços) são utilizados mais que outros, e também exigem mais ou menos recursos. Para uma melhor configuração das memorias do servidor onde o stirling esta implantado, gostaria de deixar a sugestão de colocar um contador de acessos na pagina ou um painel para saber quantos acessos cada ferramenta teve e suas estatisticas. Talvez um painel de contador que contenha os acessos por hora/dia/mes, etc. Assim poderemos alocar melhores recursos e melhor aproveitamento dos processadores e serviços no servidor e também realocar de maneira mais eficiente os heaps do java.

Obrigado novamente

**Comment by Frooodle** [comment]
This is already a api endpoint for this you can use
It should be in the api documentation 
Are you saying you want a UI for this?

**Comment by Frooodle** [comment]
The api shows total endpoint hits for both page loads and requests 
And can be total or per endpoint 

It doesn't do day month stats though
