### ISSUE TITLE
README calls the GUI "intractable", typo?

### ISSUE THREAD

**Issue by benjamin051000** [Frooodle/Stirling-PDF#229]
https://github.com/Frooodle/Stirling-PDF/blob/987d9b0502336af67a82a0a8e6afebc51258dcd5/README.md?plain=1#L24

Intractable is a negative word, meaning difficult to manage or deal with. (see https://www.merriam-webster.com/dictionary/intractable)

Was this meant to say "interactive"?

**Comment by Frooodle** [comment]
Yes that is correct, let me change that now thankyou!

**Comment by Frooodle** [comment]
Just changed now, thanks again
