### ISSUE TITLE
Idea: Removing/deleting pages from PDF

### ISSUE THREAD

**Issue by PiotrEsse** [Frooodle/Stirling-PDF#23]
It would be great to have ability to delete pages from multipage PDF document.

**Comment by Frooodle** [comment]
This is kinda here already as part of the reorganise step
Any pages not included are deleted
Like typing 1-5 10-20 would delete pages 6-9

But having its own step makes sense too
Will add later

**Comment by Frooodle** [comment]
Added as part of
https://github.com/Frooodle/Stirling-PDF/pull/26
