### ISSUE TITLE
[Feature Request] - PDF File Separator 

### ISSUE THREAD

**Issue by nodecentral** [Frooodle/Stirling-PDF#235]
Hi @Frooodle 

Sorry if this has been requested before, i did do a quick search but couldn’t see anything 

**Situation**
I will often get a build up of various documents that i’ll need to scan in and sort out, but i have to do them in batches in order to create separate pdf files, which can take quite a bit of time. 

**Ask**
I was wondering if it was possible to have something that could allow me to scan everything in all in one go, which would create a single large pdf (= pdf123.pdf), but then have a way in Stirling PDF to read it and split it out into the require batches (resulting in multiple files = pdf123-a.pdf, pdf123-b.pdf etc.)

**References**
The following explains how barcode pages are used to do this, - https://www.scantastik.com/hardware/kodak-scanners/bar-codes.html - but maybe Stirling PDF could do something similar / perhaps more simplified / intelligent :-)

**Comment by Frooodle** [comment]
You might have to give more info on your usecase

Stirling pdf can split documents 
Are you wanting some folder watch for this or via website... and how are you meaning to pass what page to split at in your example usecase?

**Comment by nodecentral** [comment]
> You might have to give more info on your usecase

Let’s say I have a PDF file that is made up of various different bills, statements, letters etc. Could Stirling PDF be set up to detect where a bank statement page then becomes a letter I received from the doctor ? I expect this is not easy to do, even if you had AI, but I was wondering if was to add or stamp something on the page where I’d want a split to occur it could ? If thats not easy to do, then when I scan all my mail in, what if i scanned in a divider page that Stirling PDF would look for to know that’s the end of a batch of pages I want extracted as a separate file..

Does that help ?

**Comment by Frooodle** [comment]
Divider page would help 
I know people have thought about split on blank page before as example 

Detecting the difference in document would be hard
I can't think of any nice way to do this even with computer vision 
  unless it was very obvious, say going from a4 to a5 or paper colour etc 

Keep in mind since you're scanning here all logic we would use is realistically image detection so it's a bit more advanced

**Comment by Frooodle** [comment]
I can look into doing a divider page detection 
Maybe even have a custom divider page option you can print out (some qr code) 
So that it's super easy to detect so process of detection and split is super fast

**Comment by nodecentral** [comment]
> I can look into doing a divider page detection
> Maybe even have a custom divider page option you can print out (some qr code)
> So that it's super easy to detect so process of detection and split is super fast

That would be amazing, admittedly being able to detect something on the page would be ideal, just to avoid having to print out loads of divider pages - but,  i can see how the divider page route would be much much easier to do, and potentially a chance for a bit of Stirling PDF marketing :-) defer to you but can’t wait to test it out … 👍

**Comment by Frooodle** [comment]
I don't see how I could detect different content otherwise
Would be far too complex with huge false positives

I like the idea of the marketing though :')

**Comment by Frooodle** [comment]
Done in V0.11.0

![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/db58c78a-cc91-494c-a018-aee3f6b5df4b)
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/b87593c0-9edd-46ef-b6a5-7f14e72f8fca)
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/f0ca311f-ff67-4c5c-ade9-4855a3a6952b)

**Comment by nodecentral** [comment]
Hi @Frooodle , thanks so much for releasing this capability, I’ve just had a quick go and noticed something interesting (certainly for me with a scanner that scans both side) it removes the barcoded pages, but in some cases it does not always remove the following page scan (I’m assuming this is because it expects that back of that page to be completely blank, where in my case on a few of the print outs you can see a faint outline of the barcode on the back of the page.  (See image below)

![IMG_3502](https://github.com/Frooodle/Stirling-PDF/assets/4349292/10226cdd-9c81-4c52-a44f-cdeae0ed482e)

**Comment by Frooodle** [comment]
Ahh it's expecting single side scanning not double!
I will add a setting to choose between single and double  it will skip the barcode page and the page after it as well if double

Will that work for you?

**Comment by nodecentral** [comment]
Many Thanks @Frooodle 

I would expect most people who do batch scanning will have a duplex scanner, (as you can just let it run) otherwise you will have to feed each page in one at a time and then rotate - so if you are looking for a default i’d propose using duplex as that..

Hold on - Maybe another (better) option is for me to print the barcode on both the front and back page, that way Stirling-PDF can be more decisive about what pages are separators ? Would that cause any issues if you see two barcode pages back to back ?

**Comment by nodecentral** [comment]
@Frooodle - quick question, does it care what size the separator barcode is, can i resize the image ?

**Comment by Frooodle** [comment]
Not sure if it would cause issue but i should probably code for that usecase to be safe anyway... I'll make sure it supports that.
I think adding a duplex mode makes sense anyway for people that dont want to print double sided

As for QR code size it shouldnt matter much as long as its visible. 
you are welcome to change it i attched .odt file
[Copy of Stirling PDF Auto Splitter page divider.odt](https://github.com/Frooodle/Stirling-PDF/files/12166042/Copy.of.Stirling.PDF.Auto.Splitter.page.divider.odt)

**Comment by Frooodle** [comment]
Ill have a fix for both the above tomorrow :)

**Comment by Frooodle** [comment]
Try latest version
Let me know how it goes
Should support double sided and single sided with duplex mode tickbox

**Comment by nodecentral** [comment]
Works great ! Thanks @Frooodle
