### ISSUE TITLE
Idea: PDF document preview

### ISSUE THREAD

**Issue by PiotrEsse** [Frooodle/Stirling-PDF#24]
It would be great to have some form of preview for PDF. Now when I want to ie: rearrange PDF i need to check locally what pages I need to rearrange and than provide that in StirlingPDF. It would be great to do this interactively.

**Comment by Frooodle** [comment]
This is a long term goal, won't be added anytime soon but hopefully eventually

**Comment by Frooodle** [comment]
@PiotrEsse Coming next release!

**Comment by Frooodle** [comment]
Done as part of 0.6.0 release!
