### ISSUE TITLE
There was an error in adding watermark when using Chinese characters

### ISSUE THREAD

**Issue by Dylanchouxd** [Frooodle/Stirling-PDF#241]
Hi Frooodle,

First of all, the tool is amazing, very helpful to my job, thank you very much for your contribution!!

I just installed the docker version and ran into a problem. When i use Add Watermark function, and try to enter Chinese characters, then the page output some error.

It look like about the font not support Chinese. Maybe you have an idea?

<img width="1249" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/26562051/f9940c52-8a21-4246-8b6e-b18cad5378bd">

Watermark Text: 测试测试

Best regards,
Dylan.

**Comment by Frooodle** [comment]
Can you please show the stacktrace when possible, it helps with issues

**Comment by Frooodle** [comment]
I have fixed issue in my local branch but wont be making a new release for another week or so

**Comment by Dylanchouxd** [comment]
> I have fixed issue in my local branch but wont be making a new release for another week or so

It's okay, I can wait for the next release, Thank you very much :)

**Comment by silva6** [comment]
Has the same problem. Can this fix to be release now? Thank you  :)

**Comment by Frooodle** [comment]
Yeah I'll make a early release this weekend for it :)

**Comment by Frooodle** [comment]
Done in 0.10.3 !
