### ISSUE TITLE
PDF to image : 1200 DPI ?

### ISSUE THREAD

**Issue by KatyPurry** [Frooodle/Stirling-PDF#242]
Hello,

PDF to image seems blocked to 600 DPI, when I enter 1200 / 2400 DPI, the image size is the same as 600 DPI, is it intended ? Thank you

**Comment by Frooodle** [comment]
This could be a limitation of the library I use to render the images 

I'll have a check and see what i can do,
Not intended to have any limits

**Comment by KatyPurry** [comment]
Thank you !
