### ISSUE TITLE
[Bug] word to pdf using libreoffice doesn't support chinese characters 

### ISSUE THREAD

**Issue by Frooodle** [Frooodle/Stirling-PDF#246]

**Comment by Frooodle** [comment]
Should be fixed in 0.10.3 or at least might be.. please let me know.if not

**Comment by lostmaniac** [comment]
[新建 Microsoft Word 文档.docx](https://github.com/Stirling-Tools/Stirling-PDF/files/14738536/Microsoft.Word.docx)
The language pack has been installed, and the Chinese docx or doc converted to PDF will be garbled. Above is the test file.
