### ISSUE TITLE
[Feature request] Multitool - Drag and drop to add source file (and new pages)

### ISSUE THREAD

**Issue by jufy111** [Frooodle/Stirling-PDF#248]
The other tools have the ability to drag and drop files from explorer (rather than navigate through the popup). It would be good to have this feature in the multitool too.

**Comment by webysther** [comment]
For all tools will be nice, compress or ocr...

**Comment by Frooodle** [comment]
> For all tools will be nice, compress or ocr...

If this isn't for the other tools then it was removed by mistake
They should support that already

**Comment by webysther** [comment]
I got this on rotate:

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/dd09f43c-afce-455c-be20-fa7c02b09c0d)

And multitool have a area is great to not being precise to browse area:

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/ae80e6e6-29e5-4630-9e19-85f5645d76e8)

Any change to change all tools to looks like this?

![image](https://github.com/Frooodle/Stirling-PDF/assets/750007/ec789b04-5891-4f07-9d9a-383f5d71975a)

The drop area is all screen.

**Comment by Frooodle** [comment]
@webysther  Done for all other than multitool as logic was slightly different
