### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by PiotrEsse** [Frooodle/Stirling-PDF#25]
I would like to translate Stirling to Polish. Earlier in other systems I use Weblate. Maybe You would consider to make Your app multilanguage and set new projest in [weblate ](https://weblate.org/pl/)

**Comment by Frooodle** [comment]
I plan to add localisation eventually 
I can add english and French myself
Others will have to be added by community over time

**Comment by PiotrEsse** [comment]
Weblate is great, easy to configure and can automatically get and publish translation files back on your repository.

**Comment by Frooodle** [comment]
I can make something similar in Java spring https://www.baeldung.com/spring-boot-internationalization

**Comment by louiskram** [comment]
Hi, I would also be interested in a translation. I could contribute German.

**Comment by Frooodle** [comment]
I plan to add this this weekend if i have time so will let you know

**Comment by Frooodle** [comment]
@louiskram  @PiotrEsse  Added translations as part of https://github.com/Frooodle/Stirling-PDF/pull/35
Added a quick readme for this https://github.com/Frooodle/Stirling-PDF/blob/main/HowToAddNewLanguage.md
Let me know if you have any questions
Will keep this issue open so others can reference

**Comment by trietdo** [comment]
How to add new language for docker?

> @louiskram @PiotrEsse Added translations as part of #35 Added a quick readme for this https://github.com/Frooodle/Stirling-PDF/blob/main/HowToAddNewLanguage.md Let me know if you have any questions Will keep this issue open so others can reference

**Comment by Frooodle** [comment]
> How to add new language for docker?
> 
> > @louiskram @PiotrEsse Added translations as part of #35 Added a quick readme for this https://github.com/Frooodle/Stirling-PDF/blob/main/HowToAddNewLanguage.md Let me know if you have any questions Will keep this issue open so others can reference
> 
> 

To add a new language to stirling pdf you do as instructed in that link and then merge it into Stirling-PDF 
They will then be included in the next release
