### ISSUE TITLE
[Feature Request] Scan to directly and host PDF files

### ISSUE THREAD

**Issue by Dvalin21** [Frooodle/Stirling-PDF#255]
This tool is awesome by the way. I wanted to see adding this feature would be possible. It would be awesome to be able to scan directly to and host pdf files. Being able to do this all in one place. This would be geared more for private use, which then a person can just put it behind nginx or the like to keep people out (or just not make available to the www) Thanks.

**Comment by Frooodle** [comment]
As far as I know scanning software can not come website and has to be local to pc or with some companion app 

As for PDF hosting its not the direction I want for this app at moment but maybe later
I do plan to temporarily host pdfs for group signing and things in future so maybe as part of that

**Comment by Dvalin21** [comment]
> As far as I know scanning software can not come website and has to be local to pc or with some companion app
> 
> As for PDF hosting its not the direction I want for this app at moment but maybe later I do plan to temporarily host pdfs for group signing and things in future so maybe as part of that

Thanks for the reply. You are right, you have to use a third party software between the scanner and the website. This is what paperlessngx does to allow for direct scanning. https://github.com/manuc66/node-hp-scan-to. Look forward to seeing whats next for the project

**Comment by Irish-link** [comment]
Group Signing would be amazing!

**Comment by Frooodle** [comment]
scanner support isnt planned sorry!
