### ISSUE TITLE
Docker Image error

### ISSUE THREAD

**Issue by Typhonragewind** [Frooodle/Stirling-PDF#263]
Getting this error after updating the docker image:

`2023-07-06T14:55:14.525643602Z Copying original files without overwriting existing files

2023-07-06T14:55:14.529484222Z /scripts/init.sh: line 9: exec: java: not found`

**Comment by Frooodle** [comment]
This is caused by init.sh containing invalid line endings 
I have got it a few times and run dos2unix on it 
or open in notepad++ and do Edit -> EOL conversion -> Unix

But i am not having this issue on latest tag so curious...

**Comment by Typhonragewind** [comment]
I was using the latest tag, but implicitly. I changed to to explicitly state "latest"and it seems to be fixed.
