### ISSUE TITLE
local.server.port environment variable is not being used by docker tomcat config

### ISSUE THREAD

**Issue by jenishngl** [Frooodle/Stirling-PDF#271]
I tried setting up local.server.port to a different port other than 8080 and still the docker was running on 8080 since the tomcat is using 8080 always

**Comment by jenishngl** [comment]
I have so many other services running via docker and port 8080 is already
in use. So I just wish to change the port for this one since I am setting
this up as new

--Jenish

**Comment by Frooodle** [comment]
I still dont understand the need for this,
Dont you just change the host port in your docker configuration?
such as
ports:
      - '8080:8080'
   
to

ports:
      - '8181:8080'

**Comment by jenishngl** [comment]
> I still dont understand the need for this, Dont you just change the host port in your docker configuration? such as ports: - '8080:8080'
> 
> to
> 
> ports: - '8181:8080'

Yes, I already tried this.  But still fails to install with [Coolify](https://github.com/coollabsio/coolify) on my Raspberry pi 4

While i tested this locally in windows machine and it worked perfectly fine.

Will check with the Coolify logs first and then their team. Thanks!!
