### ISSUE TITLE
Feature Request: PDF File Information Viewer

### ISSUE THREAD

**Issue by lukasgabriel** [Frooodle/Stirling-PDF#272]
A mode that shows information about the uploaded PDF file such as
- its **version** of the PDF format (1.3, 1.4, ...)
- **standards** compliance (PDF-A etc.)
- the **encryption** algorithm, key length, and KDF used (for password-protected PDFs)
- standard **file info** such as author, size, word/character count
- name and **certificate** for signed PDFs
- **fonts** used and/or embedded
- **security policies** (is editing allowed, is printing allowed, ...)
- embedded **JavaScript**
- **application of origin**
- **page dimensions**
- embedded **copyright information**

Of course, any subset of these features would also be a great addition  :)
I just listed all the properties I could think of, and those that my PDF application of choice (PDF-XChange Editor) is able to extract.

**Comment by lukasgabriel** [comment]
PS: Keep up the great work, this is an amazing and incredibly helpful tool!

**Comment by Frooodle** [comment]
Good idea! I'll add it to my todo list :)
