### ISSUE TITLE
[Bug] Ordem de arquivos não aparece quando arrastado e solto versus selecionado

### ISSUE THREAD

**Issue by XSoueiX** [Frooodle/Stirling-PDF#275]
Eu estava testando a função de merge e percebi que quando arrasto e solto os arquivos não aparece a opção para selecionar a ordem.

Creio que seja um bug.

### Drag & Drop
<img src="https://github.com/Frooodle/Stirling-PDF/assets/40127216/44ec080e-f2ac-48f2-b31f-aace7bd72f12" width=60%/>

### Selected
<img src="https://github.com/Frooodle/Stirling-PDF/assets/40127216/0273b4c6-20e9-482b-a6c4-13ecffb1081b" width=60%/>

Estou utilizando a versão 0.10.3 no Docker

**Comment by Frooodle** [comment]
Thanks ill take a look

**Comment by Frooodle** [comment]
Fixed in V0.11.0
