### ISSUE TITLE
Sign PDF: Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by davide-ruota** [Frooodle/Stirling-PDF#285]
In version 0.11 whenever I try to use SIGN PDF, I receive the following error message: 

Error: 500 Internal Server Error
Failed to read font directory for path: /sign

I'm using docker with image: frooodle/s-pdf:latest and this is an extract of docker log:

```
stirling-pdf_1  | 2023-07-26T09:56:02.817Z ERROR 1 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: Failed to read font directory] with root cause
stirling-pdf_1  | 
stirling-pdf_1  | java.nio.file.NoSuchFileException: src/main/resources/static/fonts
```

**Comment by Frooodle** [comment]
Can you try pull latest version and see if that fixed it

**Comment by davide-ruota** [comment]
Hi,
I tried pulling the latest version as suggested, but the issue still persists.

**Comment by NeilJared** [comment]
It persists for me too

**Comment by Frooodle** [comment]
Please try in v0.11.2

**Comment by davide-ruota** [comment]
I am happy to report that the issue has been resolved.
Thank you for your help!
