### ISSUE TITLE
Remove Pages - URL incorrect on Home page

### ISSUE THREAD

**Issue by shomilsaini** [Frooodle/Stirling-PDF#29]
Remove Pages on home page redirects to /remove-pages which throws error
![image](https://user-images.githubusercontent.com/46788173/216742175-5b9e054b-346f-4fb6-b5b3-432341b420ea.png)

It works from top navigation as it redirects to /delete-pages

I believe it should be remove-pages and top nav should match that to be consistent with naming conventions

Cheers!

**Comment by Frooodle** [comment]
fixing in todays update, thanks for finding this

**Comment by Frooodle** [comment]
Fixed, in latest release
