### ISSUE TITLE
how can i run this project on server anyone guide me

### ISSUE THREAD

**Issue by amitdevopsschool** [Frooodle/Stirling-PDF#291]
how can i run this project on server anyone guide me

**Comment by Frooodle** [comment]
Docker or direct server?

**Comment by Frooodle** [comment]
But yes have a look at the how to use section in the readme

**Comment by amitdevopsschool** [comment]
> Docker or direct server?

i want to run on linux server

**Comment by Frooodle** [comment]
So you can either install docker and use the docker instructions or just follow the run locally instructions for Linux

**Comment by amitdevopsschool** [comment]
@Frooodle thanks lets try to my best acknowledge
