### ISSUE TITLE
Question - Does it rely on internet services/css/anything?

### ISSUE THREAD

**Issue by TopBanana123** [Frooodle/Stirling-PDF#305]
First of all, thanks for making this. This is exactly what I have been looking for

Does this rely on the internet for anything? I'm wanting this to work even with no internet. I've had issues in the past with Web interfaces hosted locally, yet referencing CloudFlare for css etc, which then breaks it when there is no internet

Thanks!

**Comment by Frooodle** [comment]
Fully 100% local working 
No external css or js

**Comment by TopBanana123** [comment]
Thank you!

**Comment by Frooodle** [comment]
That's to many variations and docker types for a mix match with all that

**Comment by Frooodle** [comment]
Docker file isn't bad idea though `

**Comment by wakawakaaa** [comment]
@Frooodle I hope you are doing well, is there any news regarding the Docker file which can produce image which works complete offline? Thanks

**Comment by Frooodle** [comment]
Sorry busy with other work and tasks at the moment

**Comment by Frooodle** [comment]
created a dockerfile-fat which people can use!
You can build the new docker file locally, will also upload to dockerhub for next release

**Comment by wakawakaaa** [comment]
Thanks a lot.
