### ISSUE TITLE
[Feature Request] Merge tool - sort by name, last modified etc.

### ISSUE THREAD

**Issue by jufy111** [Frooodle/Stirling-PDF#318]
Currently if you drop a bunch a PDFs into the merge tool, they are just arrange randomly.

**Comment by Frooodle** [comment]
Oh I like the idea,  I'll get this done

**Comment by Frooodle** [comment]
added a 
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/e9291919-2209-4e6d-adaf-c197de46e697)
 button in UI
 
 and also 
 "orderProvided", 
"byFileName", 
"byDateModified", 
"byDateCreated", 
"byPDFTitle"

via api call

**Comment by JefPresotto** [comment]
Olá, de fato não existe uma ordem, seria interessante ter como especificar a ordem dos arquivos que serão unificados.
