### ISSUE TITLE
SIMO API Responses

### ISSUE THREAD

**Issue by Samurai1201** [Frooodle/Stirling-PDF#328]
Im trying to use the /extract-image-scans endpoint of the API. 

`curl -X 'POST' \
  'http://192.168.178.109:7433/extract-image-scans?angle_threshold=5&tolerance=20&min_area=8000&min_contour_area=500&border_size=1' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'fileInput=@20230825_172309.PDF;type=application/pdf'`

The response code returns as 200, so it should have been successful.

But I only receive the following response contents:

[response.txt](https://github.com/Frooodle/Stirling-PDF/files/12452842/response.txt)

I was expecting either a download link or a utf-8 encoded .zip.

Other API endpoints with SISO like /repair respond as expected though.

I am unsure whether im doing something wrong or if this is generally not working properly?

**Comment by Frooodle** [comment]
I think the issue is with the handling of Form data vs parameter data
can you try run it like
```
curl -X POST "http://192.168.178.109:7433/extract-image-scans" \
     -H "accept: */*" \
     -H "Content-Type: multipart/form-data" \
     -F "fileInput=@20230825_172309.PDF;type=application/pdf" \
     -F "angle_threshold=5" \
     -F "tolerance=20" \
     -F "min_area=8000" \
     -F "min_contour_area=500" \
     -F "border_size=1"
```

**Comment by Samurai1201** [comment]
This works perfectly for me
Thanks for the quick response

The command I posted previously was created using the api documentation of stirlingpdf with swagger ui
It would be cool if the documentation could also be fixed to reflect this behaviour

Thanks a lot for your work

**Comment by Frooodle** [comment]
Yeah I have checked on this and it seems swagger doesn't play nice with the form inputs I have 

I'll make a note in the swagger description but not much else I can do :( 

Glad it works!
