### ISSUE TITLE
[Feature Request] - Adding images (maybe other file types too) directly in Multi Tool

### ISSUE THREAD

**Issue by debugger24** [Frooodle/Stirling-PDF#334]
Can we have option to add images and maybe other file types too directly in Multi Tool UI itself, so user will be able to upload mix of pdf, image and other files and it will be converted to pdf on the fly before converting to final single pdf.

**Comment by Frooodle** [comment]
Duplicate of https://github.com/Frooodle/Stirling-PDF/issues/278

Do plan to support in future
