### ISSUE TITLE
How to change default port in Synology docker after installation?

### ISSUE THREAD

**Issue by dgulan** [Frooodle/Stirling-PDF#340]
I installed the s-pdf in the Synology docker, using a wizard installation mode, not using Docker Compose. After installation, the setting is as follows:

<img width="585" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/28797169/d6a88199-e349-46e3-b872-b70b969b0dfd">

**The default port is 8080, I want to change it to another port like 8088.**
I don't know how to change it. Thanks for your help!
Is it possible to change the port in the environment variable? Something like the command in the red box in the picture?
Thank you.

**Comment by Frooodle** [comment]
Port changing is normally handled by Docker itself 
I would assume that functionality should be exposed somewhere in the framework you are using 

As for changing the port via the app itself... I think there might be a way but let me check and get back to you (but I do think your app should support native docker port handling)

**Comment by Frooodle** [comment]
I know 
https://mariushosting.com/how-to-install-stirling-pdf-on-your-synology-nas/

Recommends doing it via portainer which gives you the docker compose and port control for synology

**Comment by BeckeBauer** [comment]
open the container manager app, select the container and stop it
select the settings tab and remove the port (if set)
![image](https://github.com/Frooodle/Stirling-PDF/assets/51003649/f37155bd-9952-433d-907d-6535ae3c7e06)
click add and enter as container port 8080 and as local port the port you want to use:
![image](https://github.com/Frooodle/Stirling-PDF/assets/51003649/975fcc6f-bd0c-402d-a277-11f7864dde01)
