### ISSUE TITLE
settings.yml not working

### ISSUE THREAD

**Issue by Raptor05** [Frooodle/Stirling-PDF#348]
I've updated my container to version 0.13.1. Since the environment variables has been changed, the deployment of the container failed. So I removed them all and instead, added the settings.yml file to the /configs path (using volume mapping in docker compose).
But unfortunately the settings are ignored. Name, description and Tab Name are not adjusted.
In my opinion, stirling-pdf is ignoring the settings.yml file at all.

**Comment by Frooodle** [comment]
Can you share your docker logs and settings file?

**Comment by Frooodle** [comment]
Also worth noting you don't need to remove environment variables
They just changed naming

**Comment by Raptor05** [comment]
> Can you share your docker logs and settings file?

Sure, here are the two files.
[_Stirling-PDF_logs.txt](https://github.com/Frooodle/Stirling-PDF/files/12536824/_Stirling-PDF_logs.txt)
[settings.yml.txt](https://github.com/Frooodle/Stirling-PDF/files/12536831/settings.yml.txt)
(renamed yml to txt to be able to upload file)




> Also worth noting you don't need to remove environment variables They just changed naming
> 
> (However I do want to figure out what's causing the settings.yml issue for you)

Do you have a list of the new environment variable names?


Thanks for your investment! 😊

**Comment by Frooodle** [comment]
ApplicationProperties [security=Security [enableLogin=false, initialLogin=InitialLogin [username=username, password=MASKED], csrfDisabled=true], system=System [defaultLocale=de-DE, googlevisibility=false, rootURIPath=null, customStaticFilePath=/customFiles/static/, maxFileSize=null], ui=null, endpoints=Endpoints [toRemove=[], groupsToRemove=[]], metrics=Metrics [enabled=true], automaticallyGenerated=null, autoPipeline=null]
rateLimit=null


This shows its being read fine 
Your UI has a # at start which you need to remove which is why it's reading it as null here

**Comment by Frooodle** [comment]
To reference my docs for environment vars 

Environment variables are also supported and would override the settings file For example in the settings.yml you have

system:
  defaultLocale: 'en-US'

To have this via an environment variable you would have SYSTEM_DEFAULTLOCALE

By combining each layer with _ between

**Comment by Raptor05** [comment]
> ApplicationProperties [security=Security [enableLogin=false, initialLogin=InitialLogin [username=username, password=MASKED], csrfDisabled=true], system=System [defaultLocale=de-DE, googlevisibility=false, rootURIPath=null, customStaticFilePath=/customFiles/static/, maxFileSize=null], ui=null, endpoints=Endpoints [toRemove=[], groupsToRemove=[]], metrics=Metrics [enabled=true], automaticallyGenerated=null, autoPipeline=null] rateLimit=null
> 
> This shows its being read fine Your UI has a # at start which you need to remove which is why it's reading it as null here

My bad, thanks. That was stupid of me 😂 It's working now like a charm!

> To reference my docs for environment vars
> 
> Environment variables are also supported and would override the settings file For example in the settings.yml you have
> 
> system: defaultLocale: 'en-US'
> 
> To have this via an environment variable you would have SYSTEM_DEFAULTLOCALE
> 
> By combining each layer with _ between


Ah okay, now I understand it. Thanks for that, too.
