### ISSUE TITLE
RestAPI and converting PDF to PNG

### ISSUE THREAD

**Issue by schmittg25** [Frooodle/Stirling-PDF#352]
So I'm trying to follow the documentation but no matter what I do, I get errors. Using the swagger ui, I upload a PDF and click execute but I don't get back a png. Is this section working currently or is it just a placeholder?

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/issues/328

This might describe the issue better

I am trying to get swagger documentation to play nice 
It's good to show parameters etc but it needs to all be in multipart form 
Which swagger doesn't want to do

**Comment by Frooodle** [comment]
Documentation within swagger should be fixed in latest release
https://github.com/Frooodle/Stirling-PDF/releases/tag/v0.14.0
