### ISSUE TITLE
bug: docker fails to load container due to networking error

### ISSUE THREAD

**Issue by zombiehoffa** [Frooodle/Stirling-PDF#354]
using this docker-compose: 

version: '3.3'
services:
    s-pdf:
        ports:
            - '8063:8080'
        image: frooodle/s-pdf

I get this error trying to bring  it up:

failed to create network stirlingpdf_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

I've got a bunch of other containers running on this host with no problem (that's why I had to adjust the port). not really sure where to go from here, google wasn't that helpful.

**Comment by Frooodle** [comment]
All I can suggest is double check your ports are not conflicting 

1. Check Existing Networks:
   Run the following command to list existing Docker networks and check if any of them have consumed most of the available IP addresses or ports:
   ```
   docker network ls
   ```

Maybe prune if you have unused ones
   ```
   docker network prune
   ```

**Comment by zombiehoffa** [comment]
Pruning seemed to work, even though it really shouldn't have, weird.
