### ISSUE TITLE
[Version 0.14.2] settings.yml overwrite at each start-up

### ISSUE THREAD

**Issue by LapinFou** [Frooodle/Stirling-PDF#376]
The section **ui** in the config file `settings.yml` is overwritten to its default value each time the docker image is launched.

**Comment by ebildebil** [comment]
I observed the same on my install today.

**Comment by Frooodle** [comment]
Should be fixed, can you confirm?

**Comment by LapinFou** [comment]
> Should be fixed, can you confirm?

On my Synology NAs (Portainer), I can confirm the issue has been fixed. 😍
Thanks for this quick fix. 👍
