### ISSUE TITLE
Signatures appear vertical when signing document

### ISSUE THREAD

**Issue by HiDef888** [Frooodle/Stirling-PDF#377]
When I add my drawn signature to a vertical PDF, then redownload the file, the added signature is completely vertical on the right-hand side of the page - not in the location where I placed it on the PDF (bottom left)

**Comment by goekhanm** [comment]
@HiDef888 How did you solve the Problem. I have the same issue. Trying to insert a png or jpeg as a signature

**Comment by Frooodle** [comment]
Can you run the pdf through the pdf repair and see if to changes anything?

**Comment by goekhanm** [comment]
Thx @Frooodle repairing solved the problem
What also solved the problem is to use "view PDF" (with the unrepaired PDF) and insert the image from there.
Thanks for your fast help

**Comment by goekhanm** [comment]
@Frooodle forgot to mention. Repair after signing didn't solve the issue
