### ISSUE TITLE
OCR does not work 

### ISSUE THREAD

**Issue by NeilJared** [Frooodle/Stirling-PDF#380]
Version 0.14.3, as 0.14.2 and 0.14.1, I am using ENG and a 1 page pdf, does not recognizer anything and crashes, giving error 504 with no record. Tried using other languages installed and same results. I tried with a bigger pdf, and same results. 5000Mb size limit established, as default. Any ideas?

**Comment by Frooodle** [comment]
Can you show what options you are selecting as well as the docker log?

**Comment by Frooodle** [comment]
I have tested and it worked on my side so need to know what makes it unique in your case, let me know if i can also test with your PDF file

**Comment by erwin1024** [comment]
I had to put a symlink from .../tesseract-ocr/5/ to /4.00 to get it to work.

**Comment by Frooodle** [comment]
How are you hosting this? 
Is it using our docker image package or another such as cloudron?

**Comment by erwin1024** [comment]
Bare metal install from https://github.com/Frooodle/Stirling-PDF/blob/main/LocalRunGuide.md on an lxc via proxmox.
I could not install the suggested java-package but java-common did it.

**Comment by Frooodle** [comment]
ahhh right now i guess baremetal will have issue due to version updates in our dependencies so using latest versions of everything isnt best idea for that.
Ill try update docker image with latest versions and then hardcode the versions for both docker and bare metal and allign everything to resolve this in future

**Comment by erwin1024** [comment]
Thank you!
Well, I guess this is the reason for more and more docker images: easier to maintain. But I dont like docker the much, I separate applications on virtual machines, the are easier to debug and to backup, I think.

**Comment by olni** [comment]
@erwin1024
..thx for this suggestion - i did the bare metal way as well and used debian bookworm which uses tesseract-ocr/5/
so the symbolic link does the trick for me too. ;-) :+1:

**Comment by NeilJared** [comment]
It was my fault. Changed traineddata files used and works right with any language (extended).

**Comment by NeilJared** [comment]
It was my fault. Changed traineddata files used and works right with any language (extended).
