### ISSUE TITLE
Improve Display of Page Width and Height

### ISSUE THREAD

**Issue by lawfulsoftware** [Frooodle/Stirling-PDF#382]
The dimensions of a letter-sized page from Get Info on PDF are reported as:

Width: 612
Height: 792

This seems to be in pixels and based upon 72 ppi which is probably not what people are expecting to see.  Perhaps it can be displayed in cm and inches in addition to pixels along with the ppi value.

Additionally, the "Standard Size" value is "Custom" whereas it should be Letter.

Thank you @Frooodle for developing this wonderful project.

**Comment by Frooodle** [comment]
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/e5864cee-d9cd-4884-b3aa-e459cefd0adc)

**Comment by Frooodle** [comment]
ahh let me round these numbers actually

**Comment by Frooodle** [comment]
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/ada8aece-ee2d-43bf-a938-c50cbf828a30)
