### ISSUE TITLE
Extract Images Bug

### ISSUE THREAD

**Issue by lawfulsoftware** [Frooodle/Stirling-PDF#384]
I tested the Extract Images module with an eleven-page PDF file.  The PDF file contains two images on page 1 and one image on page 2. The remaining pages are entirely text.

The output is a ZIP file with 33 items.  The files are in the format {{original filename}}_{{image number}} ({{Page #]}).png.

Input:

<img width="572" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/96336813/a0c94004-53b5-4911-87fb-6b091b3e5623">

Output:

<img width="810" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/96336813/a3f67819-3499-4f72-a2a1-b8ec0ad19240">

The page numbers are wrong as the highest page # is 12 while the PDF only has 11 pages.  Each of the images is included 11 times for a total of 33 files.

**Comment by Frooodle** [comment]
Ive fixed the page numbering issue but cant reproduce the duplication you are seeing here... i am wondering if its unique to your PDF type... i will see what i can do

**Comment by Frooodle** [comment]
Since i cant find bug ill just add a check for duplicated images and avoid the second readd
