### ISSUE TITLE
Feature Request - Bigger text input

### ISSUE THREAD

**Issue by astronyu** [Frooodle/Stirling-PDF#394]
When choosing "Text input" in "Sign" option, would it be possible to have the text input area to be a box with unlimited rows instead of one liner?

This way instead of the text added into the pdf in one line e.g. "This is the first sentence. This is the second sentence", it can be added in separate rows 
e.g. 
"This is the first sentence.
This is the second sentence
This is the third sentence"

or perhaps a WYSIWYG type of text input with formatting?

**Comment by DimK10** [comment]
Hi! @Frooodle! Can i try this one? Also, can i consider a free option such as TinyMCE as a WYSIWYG editor, or should i just try to add a textarea?

**Comment by Frooodle** [comment]
TinyMCE doesn't have a unlimited use option right?
However certainly, if you find a fully free option you are welcome to use it as long as it's size is reasonable

**Comment by DimK10** [comment]
@astronyu  Hey! For the time being, i have added a text area as a quick enhancement! Feel free to check it out!

**Comment by astronyu** [comment]
> @astronyu Hey! For the time being, i have added a text area as a quick enhancement! Feel free to check it out!

Thank you!
