### ISSUE TITLE
Unable to enable login authentication

### ISSUE THREAD

**Issue by derek-sparks** [Frooodle/Stirling-PDF#417]
I have set DOCKER_ENABLE_SECURITY to true in the environment variables and SECURITY_ENABLE_LOGIN in settings.yaml but the app seems to be trying to download a version of Sterling-PDF-with-login.jar that doesn't exist:

```
Error: Invalid or corrupt jarfile /app.jar
Error: Invalid or corrupt jarfile /app.jar
Copying original files without overwriting existing files
**Trying to download from: https://github.com/Frooodle/Stirling-PDF/releases/download/v0.14.5/Stirling-PDF-with-login.jar**
Copying original files without overwriting existing files
```

![image](https://github.com/Frooodle/Stirling-PDF/assets/144740948/c460b719-e912-46a5-9a79-30215bf2d415)

**Comment by Frooodle** [comment]
Ahh I think current code does not support login jar for alpha tag 

I'll see if I can fix this in next release

**Comment by Frooodle** [comment]
I believe this was issue caused by older tag, can you try update?

**Comment by ontheair81** [comment]
Unfortunately I get the same error when trying to start 0.17.2-lite.

**Comment by Frooodle** [comment]
Can you try delete the image and redownload and see if it makes any difference?

**Comment by ontheair81** [comment]
Just redownloaded it and now it works. Thank you!
