### ISSUE TITLE
When I set the system language to zh-cn, there are still some parts of the interface that remain in English. Can you tell me why this is happening?

### ISSUE THREAD

**Issue by alones58** [Frooodle/Stirling-PDF#419]
When I set the system language to zh-cn, there are still some parts of the interface that remain in English. Can you tell me why this is happening?
like this-------------

> HTML To PDF
未选择任何文件

Accepts HTML files and ZIPs containing html/css/images etc required

Uses WeasyPrint

**Comment by Frooodle** [comment]
Translations are added manually via people.

So unless someone translates the new content after it's added it won't be translated and will shoe the English version

The file in question in 
https://github.com/Frooodle/Stirling-PDF/blob/main/src/main/resources/messages_zh_CN.properties

**Comment by Frooodle** [comment]
You are welcome to add translations and raise a PR to add then it would be translated in next version

**Comment by alones58** [comment]
But in the message_zh_CN.properties file, the relevant sentences have been translated, but the UI interface is still displayed in English.
---------------------------------
home.HTMLToPDF.title=HTML转PDF
home.HTMLToPDF.desc=将任何HTML文件或zip文件转换为PDF
HTMLToPDF.tags=标记、网页内容、转换、转换
----------------------------------

**Comment by Frooodle** [comment]
This is probably because the latest release is yet to pick up these changes,  I  will make a new release soon for you

**Comment by alones58** [comment]
Thank you very much for your reply, hope to solve this "issue".

**Comment by Frooodle** [comment]
Try now, latest update should include this
