### ISSUE TITLE
[Feature Request] PDF Reader (mobile friendly) with annotating etc

### ISSUE THREAD

**Issue by thebigalwisi** [Frooodle/Stirling-PDF#422]
Hi guys, 

sorry if it is one kind of stupid questions: Why not to make your software perfect and add a reader with highlight and annotating functions?

**Comment by Frooodle** [comment]
Just to add to this issue
Can be based on https://mozilla.github.io/pdf.js/web/viewer.html (some code already exists here https://github.com/Frooodle/Stirling-PDF/tree/main/src/main/resources/static/pdfjs)

Must be a standalone feature called View/Annotate PDFs

Must have all same features as above viewer.html such as page view, pen drawing input etc

**Comment by DimK10** [comment]
Im on it!

**Comment by thebigalwisi** [comment]
Wow! Guys, you are awsome! Thanks!
