### ISSUE TITLE
Customize favicon

### ISSUE THREAD

**Issue by 247no2** [Frooodle/Stirling-PDF#433]
Hello,
I would like to change the favicon on the main page, but I can't find where to do it.
Could someone maybe help me where I can set up an individual favicon?

Thanks

**Comment by Frooodle** [comment]
Quoting from the readme but 

Customise static files such as the app logo by placing files in the /customFiles/static/ directory. An example of customising app logo is placing a /customFiles/static/favicon.svg to override current SVG. This can be used to change any images/icons/css/fonts/js etc in Stirling-PDF

**Comment by RedaBousserhane** [comment]
hello I am on DOCKER how to change the logo on docker thank you
![image](https://github.com/Frooodle/Stirling-PDF/assets/8163225/ac04a361-9379-4354-9b47-43ed8a2ff57d)

**Comment by Frooodle** [comment]
Add a volume for 
/customFiles/static/

Then add favicon to it

**Comment by RedaBousserhane** [comment]
Thanks, it works great after adding the following code : - /home/your_name/stirling/customFiles/static:/customFiles/static:rw
![image](https://github.com/Frooodle/Stirling-PDF/assets/8163225/50b417b4-94bf-42b7-b408-3721cbe3e22d)
![image](https://github.com/Frooodle/Stirling-PDF/assets/8163225/19770b35-2df0-4c9a-9f34-28950f78aeb2)

**Comment by Dator77** [comment]
Hello, unfortunately it does not work for me. Does the favicon have to have a certain format or file size? 

I have created one "favicon.svg" size 32x32 and placed it in the /customFiles/static/ folder in the container.

Unfortunately this has no effect, size 16x16 did not work either. Have I misunderstood something or forgotten something?

Thanks for your help
Dator77

**Comment by Frooodle** [comment]
Is this after a app restart?

**Comment by Dator77** [comment]
Hello,

thanks for the quick reply. I have restarted the container, unfortunately no change.
I have stored the file in the following volume.

/path/on/server/volumes/static/_data/:/customFiles/static

I suspect the error is mine, maybe the favicon I generated just doesn't fit.

**Comment by ovidius1980** [comment]
Hi, 
I followed the instructions and put the new favicon.svg inside the static folder and it changed on the page. But it doesn't change on the tab. Should I do something different or change the size of the icon?

**Comment by vdrover** [comment]
Neither of these volumes work for me, even after restarting the app and clearing the cache.
```
      - $DOCKERDIR/appdata/pdf/customFiles/static:/customFiles/static/
      - $DOCKERDIR/appdata/pdf/customFiles:/customFiles/
```

**Comment by lstarrett** [comment]
This still seems to be an issue. Is there a useful workaround in the meantime?

**Comment by Frooodle** [comment]
Multiple files need repacing

favicon.ico
favicon-32x32.png
favicon-16x16.png
apple-touch-icon.png
safari-pinned-tab.svg
