### ISSUE TITLE
pdf to word problem!

### ISSUE THREAD

**Issue by Nu1i** [Frooodle/Stirling-PDF#437]
i use pdf to word , it's return error as this

nternal Server Error:Cannot run program "soffice": CreateProcess error=2, 系统找不到指定的文件。

plz.

**Comment by salsafunatiker** [comment]
I have same problem. This function "pdf 2 doc" does not work.
It "eats" all the RAM, runs for ages, but gives no result. 
At the end I need to restart container to end the process and free all RAM.

**Comment by Frooodle** [comment]
Docker or non docker 

Nginx or direct?

**Comment by Haoyi-Han** [comment]
I reproduce this error from the direct execution of the latest released executable, without docker or nginx.

**Comment by Nu1i** [comment]
oh，I installed soffice software to solve this problem.

**Comment by Frooodle** [comment]
yes if running outside of docker please install soffice!
