### ISSUE TITLE
Cannot Annotate PDF

### ISSUE THREAD

**Issue by vspaziani** [Frooodle/Stirling-PDF#446]
I cannot figure out where to go to enable or preform page annotations. According to the description "Plus on page edit features like annotate, draw and adding text and images. (Using PDF.js with Joxit and Liberation.Liberation fonts)" Can you please provide some direction oh how to enable or use the annotation features.

**Comment by Shrinkvine** [comment]
Im trying to find the same!

**Comment by Frooodle** [comment]
Ahh sorry this text was adding for the next release!
Please wait till end of day!

I will be releasing v0.15.0 with this

**Comment by Frooodle** [comment]
You can use alpha tag in meantime if you wish

**Comment by Frooodle** [comment]
Just released 0.15.0 now :)

**Comment by Frooodle** [comment]
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/93ab5564-327d-467f-8298-4c852094d237)

**Comment by marinkaberg** [comment]
Thanks a lot for annotation feature, it is extremely useful!
But something is going wrong with it in non-English UI:
**??home.viewPdf.title_ca_CA??
??home.viewPdf.desc_ca_CA??**

**Comment by Frooodle** [comment]
Ahh I will fix this within end of day, right now it has no translations available so my fix will be to default it to English untill someone provides a translation

**Comment by Frooodle** [comment]
@marinkaberg  Just released a quicker 0.15.1 to default it to english until translations are provided :)
