### ISSUE TITLE
PDF to Image only does 1st page.

### ISSUE THREAD

**Issue by shomilsaini** [Frooodle/Stirling-PDF#45]
expected - It should be converting all pages to separate images as per my understanding.

**Comment by Frooodle** [comment]
I am actually fixing this at the moment 
Although my new logic was to make one giant image
I will add option for giant or multiple

**Comment by Frooodle** [comment]
Fixed in V0.3.3

**Comment by shomilsaini** [comment]
Thanks man! Much Appreciated.
