### ISSUE TITLE
Enhancement : Change Contrast like camscanner

### ISSUE THREAD

**Issue by NexusEFR** [Frooodle/Stirling-PDF#46]
Thanks for all! its amazing project!

**Comment by NexusEFR** [comment]
look similar... https://github.com/natpuch/web-pdf-toolbox

**Comment by Frooodle** [comment]
@NexusEFR  I talked to the dev of that app on reddit :)
He is a nice guy but that project is abandoned, he uses Stirling-PDF now!

Will add support for contrast changes this next week

**Comment by Frooodle** [comment]
Not sure if there is a nicer way but only way i can see to cahnge contrast is convert the PDF to image first
I am actually reworking PDF to image currently as part of different issue so works well

**Comment by Frooodle** [comment]
Put this on hold for a bit, i coded it all but it was way to user-unfriendly to get the contrast how you want it
Will have to delay this a bit until UI rework

**Comment by NexusEFR** [comment]
Amazing Froodle! You are making a lot of progress and your project is even better! You've added new features with PDF, I'm delighted to have it on-prem! Regards, keep it up!

**Comment by Frooodle** [comment]
Done as part of V0.11.0

**Comment by Frooodle** [comment]
sorry this took so long with so many other things!

**Comment by NexusEFR** [comment]
Hello, I would like to reopen this topic to see if there are possibilities for improvement in the scanning system or post-processing treatment, particularly regarding image quality, more in line with the current style of apps like CamScanner, Genius Scan, Adobe Scan, or Office Lens. 

No desktop app has been able to achieve this; it has only been accomplished on smartphones, and it's truly post-photo processing. I want to make it clear that while the contrast and brightness functions can slightly improve a capture that is converted to PDF, the results when there are shadows, glare, very dark areas, frame distortions, or lack of parallelism, etc., show that only smartphone apps can achieve acceptable quality. Perhaps this development isn't as necessary if there are few users with these needs, but it would be the only app outside of a mobile environment that can do this.

 I have tried apps like ABBYY FineReader, NAPS2, and they are also unable to provide a real improvement in information readability. This need arises because I have been testing and requiring PDF management systems for years, and although there is nothing as versatile as StirlingPDF, this feature would be crucial for our company, which processes around 30,000 PDFs annually originating from a hospital center in the operating room, where surgical reports that include implants, authorizations, and materials used are captured in photographs that cannot leave the center. 

My company processes these to generate subsequent billing for the materials used. The problem for the sales team is that they only have one chance at capturing that image, which is then converted to PDF, and due to lighting conditions, timing, etc., the quality is often insufficient to read the text in the documents. Therefore, they must be manually run through Genius Scan (which currently complies with GDPR), but sometimes this is not done, and the unprocessed documents reach the billing department, making it an impossible task with PC tools. 

The only way would be to upload them back to the mobile, process them, export them, and then re-enter them into the document management system. However, having those automatic enhancement algorithms from these mobile apps applied to an online/offline PC platform and automated would be incredible. If there is a possibility for advanced post-processing similar to these apps, I would like to know. If it's a limitation of the system, I would completely understand.

 Thank you very much for your attention, and the application has already reached an incredible level of functions and is logically under consideration for purchase to centralize the process alongside the improvements.

**Comment by Frooodle** [comment]
Hey long time no see, always nice to see a familiar name! 
Will take a look at what is possible, our existing scanner via QR code (requires https)  importing should support edge detection with auto crop and deskew but doesnt support the

- Shadow removal
- Glare removal
- Adaptive contrast  
etc 
Are you using the exsting QR code scanner method?

**Comment by Frooodle** [comment]
We should add this as dedicated tools though, but we did try to implement a camscanner like app within stirling itself!

**Comment by NexusEFR** [comment]
Likewise, it’s great to talk with you again! You've grown incredibly with
this app; you are amazing! I am going to try to centralize the entire PDF
transformation process in your app, and I just need the image enhancement
feature.

I know it’s a difficult challenge to achieve in an app, or at least I think
so, though you have accomplished some amazing things. I have tried scanning
with QR codes, but what’s missing is the ideal solution. I even started
using the API connected to n8n and have achieved an incredible workflow for
registering all medical documents. I’m not sure if you’ve tried Genius
Scan; it's more reliable than CamScanner concerning privacy and origin, and
with fewer options, it’s very efficient and sufficient.

The automatic enhancements for images taken of a page that has shadows or
is tilted are excellent. The interface is simpler in Genius Scan, and that
would be the closest approach I'd like to see you achieve with your app. If
I get approval from management, we will purchase the server version soon; I
hope it helps you improve and develop even more.

Thank you for everything, and I hope you have great success.

Best regards!

**Comment by Frooodle** [comment]
I'll see what i can do :P
