### ISSUE TITLE
Change default Welcome.pdf in PDF View module

### ISSUE THREAD

**Issue by timconsidine** [Frooodle/Stirling-PDF#461]
Struggled to find any documentation on how to do this.
Helpful Cloudron community led to trying putting a customised `Welcome.pdf` in `customFiles/static/pdfjs/example`
Please confirm this is correct or if there is a better option.

Also please provide guidance / documentation on use of `templates` directory in `customFiles`.

Great product - thank you !

**Comment by Frooodle** [comment]
Template directory currently isn't supported only static

As for the static folder yes you should use that oathing with a new welcome.pdf in that folder 
If it doesn't work I'll investigate

**Comment by timconsidine** [comment]
Thank you @Frooodle 
Yes, the replacement Welcome.PDF at that path is being shown.
