### ISSUE TITLE
Put Results in New Browser Window (or some sort of modal) instead of same Window

### ISSUE THREAD

**Issue by funkyferdy** [Frooodle/Stirling-PDF#47]
Would help a lot when you have to do more than one Task.

BTW: Great Tool! Love it!

**Comment by Frooodle** [comment]
Been wondering about this
Open same window
Only download result
Open in new window

I think I will try make it configurable but been wondering where best to put this setting.
Ill have a think but i do plan on doing this

**Comment by Frooodle** [comment]
Added!
