### ISSUE TITLE
[Feature Request] Corrupt a PDF

### ISSUE THREAD

**Issue by Myzel394** [Frooodle/Stirling-PDF#477]
Basically make a PDF non-recoverable without making it obvious that is has been corrupted on purpose.
Similar website: https://corrupt-a-file.net/

As a student I used this website more than I'd expected and it has saved me so many times, would be awesome to help other people too :D

**Comment by Myzel394** [comment]
@Christianthelongone I think this is an easy fix for a recovery program, I'd propose to instead make the content unreadable for any PDF software

**Comment by Frooodle** [comment]
Sorry I don't think this kind of functionality has a home in Stirling pdf
I did a poll on discord and talked to a few people and generally people are against it 
A lot of unis etc actually host this software
