### ISSUE TITLE
Error when trying to extract images from a pdf

### ISSUE THREAD

**Issue by combatistor** [Frooodle/Stirling-PDF#480]
Hello everyone, I'm trying extract some images from a pdf.
I'm getting this error:
![image](https://github.com/Frooodle/Stirling-PDF/assets/6489301/de07a176-534a-44f6-a9a3-0389fc59767c)

I think the error is explicit enough, is it possible to add those dependencies to the gradle file?

```
implementation 'com.github.jai-imageio:jai-imageio-core:1.4.0'
implementation 'com.github.jai-imageio:jai-imageio-jpeg2000:1.3.0'
```
Thank you !

**Comment by Frooodle** [comment]
Sorry having to remove this, the licensing for jpeg2000 is not usable for us as a opensource application

**Comment by Frooodle** [comment]
Might be possible now found a new jpeg200 which is apache license

**Comment by phenomen** [comment]
> Might be possible now found a new jpeg200 which is apache license

I see JPEG200 support was added in `0.28.0` but I still get the same error like in OP on the latest version (`0.28.3`).

**Comment by Frooodle** [comment]
Yeah it seems even that is dependant on the other license etc.. sadly still no fix!
