### ISSUE TITLE
some guide how to add languages to OCR?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [Frooodle/Stirling-PDF#485]
I am trying to get german OCR right now. Followed your guide on how to add a different folder for the language sources, but now nothing works anymore, no OCR at all.

Having some form of install script that downloads the languages and creates an alias to use this would be awesome and I would like to create it, but for that I need to understand how adding languages work.

I already tried adding the small langpack EN to the folder, as somewhere it says this is essential

**Comment by Frooodle** [comment]
I assume this is non docker?

**Comment by Frooodle** [comment]
Did steps from https://github.com/Frooodle/Stirling-PDF/blob/main/HowToUseOCR.md

Not work?
