### ISSUE TITLE
Broken links in documentation page

### ISSUE THREAD

**Issue by pradiplimbu** [Frooodle/Stirling-PDF#487]
![Screenshot 2023-11-29 at 17 14 25](https://github.com/Frooodle/Stirling-PDF/assets/5381414/3e30248e-6240-4b10-a712-06b8bd2e345e)

`Github.io` and `three different versions` links are broken, it redirects to [`/todo`](https://todo/)

**Comment by hostile-advisor** [comment]
Hello @pradiplimbu,

I think this does not exist anymore.

**Comment by Frooodle** [comment]
This is referencing 
https://www.stirlingtools.com/
https://www.stirlingpdf.com/

I never got round to updating the website though and been focusing on GitHub currently

I will eventually get to it..

**Comment by hostile-advisor** [comment]
Is the website also open source ? @Frooodle

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF-Docs

**Comment by Frooodle** [comment]
@hostile-advisor you are welcome to change update or add however much you want

It's missing quite a few things here and there and I never got round to even making the homepage look that good 😂

**Comment by hostile-advisor** [comment]
@Frooodle Thanks mate!

**Comment by hostile-advisor** [comment]
Can be closed after merge of https://github.com/Frooodle/Stirling-PDF-Docs/pull/2
