### ISSUE TITLE
PDF to Excel feature

### ISSUE THREAD

**Issue by xdsswar** [Frooodle/Stirling-PDF#505]
Convert PDF to excel would be an  amazing feature.

**Comment by Frooodle** [comment]
I believe we have that feature implemented and be released! Will get back to you

**Comment by Frooodle** [comment]
To be released*

**Comment by xdsswar** [comment]
Thanks a lot, very nice tool you guys made. 💯

**Comment by Frooodle** [comment]
Should be a csv table extractor added now, its a work in progress let me know how it is

**Comment by xdsswar** [comment]
Tested it today and works, some times its messed up but it's ok to start. I'm coding a pdf to excel (xls, xlsx)  that keeps structure. I will repo it later and if you like feel free to use it as u like.

**Comment by xdsswar** [comment]
I'm talking about something like this 
![pdf-excel](https://github.com/Frooodle/Stirling-PDF/assets/33332351/e75a89a5-44e9-4ddb-b121-b65778bd1ae7)

**Comment by Frooodle** [comment]
oh wow thats impressive

**Comment by xdsswar** [comment]
use this https://www.e-iceblue.com/Tutorials/JAVA/Spire.PDF-for-JAVA/Program-Guide/Spire.PDF-Program-Guide-Content-for-JAVA.html

**Comment by xdsswar** [comment]
![image1](https://github.com/Frooodle/Stirling-PDF/assets/33332351/6248e6f3-eee4-4967-88b2-8e2d2de80aa1)

**Comment by xdsswar** [comment]
I see

**Comment by Frooodle** [comment]
Thats odd when i looked into spire last year i didnt see this free message, where is that?

**Comment by xdsswar** [comment]
Here 
https://www.e-iceblue.com/Download/pdf-for-java-free.html

**Comment by xdsswar** [comment]
I think you can use it, not sure 100% but since you dont charge money for the app , or you planning to do so?

**Comment by Frooodle** [comment]
Not planning to ever charge certainly not for the base app etc
I will contact their customer services to know what license their free version is registered under

i have tried spire before and it worked well so that would be awesome

**Comment by Frooodle** [comment]
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/c9370221-d368-4e41-bb2f-ed2a131b2d71)

**Comment by Frooodle** [comment]
first 3 pages of a file.. i think this is not possible to use then sadly, although its results are impressive

**Comment by xdsswar** [comment]
Yeah, the old way , but I will work out something, no matter if I need to port a c++ lib. I know I have some code to do that somewhere in my code hard drive, but I need to look for it , there is a lot, over 10 years of code.

**Comment by xdsswar** [comment]
I got a code I created back in 2021 that extract text and keeps layout 
![image](https://github.com/Frooodle/Stirling-PDF/assets/33332351/860579ff-5f30-4744-a49c-69ce1ff9870c)

I think I will be able to create a sort of skeleton with the metadata and create an excel file

**Comment by Frooodle** [comment]
closing issue ticket for now as initial request as been done
