### ISSUE TITLE
Feature Request - Halve page auto split

### ISSUE THREAD

**Issue by IngMFernandez** [Frooodle/Stirling-PDF#506]
It would be nicw if I could take any pdf that came that shows for each page of the PDF 2 pages of the original book and make a new pdf with the double amount of pages as the original by splitting each page of the original pdf in half. As this option from a competitor : https://online2pdf.com/en/cut-pdf-pages-into-halves . It'd be nice to have an open source that does this 😄. I tried the auto split option with the pdf, but it gives me 504 error o no response. I attach the pdf file that I'd  tried to split.
[Editorial_Gredos-Platón-Dialogos_IV-La_República-1988.pdf](https://github.com/Frooodle/Stirling-PDF/files/13619536/Editorial_Gredos-Platon-Dialogos_IV-La_Republica-1988.pdf)

**Comment by Frooodle** [comment]
released in latest 0.17.0!

**Comment by IngMFernandez** [comment]
Hi, thanks for taking care! I tried to split with my previusly provided .pdf file. It takes a while to do the split, more than 5 minutes. It's also not clear which kind of splitting it will do: I though that when the program said horizontal division, it was gonna draw and horizontal line and cut from there and finally, after waiting and giving it the command with two horizontal divisions and one vertical, the outputted files/pages are completely blank, I attach an image showing that blank page 
![image](https://github.com/Frooodle/Stirling-PDF/assets/146341333/57c537ac-959b-4188-b830-75f00f5edeb0)

. Vertical divisions seem to be working fine. I open the pdfs with Sumatra.

Let me know if you need meto test anything, Let me know if you need me to upload this in a separate issue.

Regards,

**Comment by Frooodle** [comment]
Fixed and added UI for visability
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/7fbf8668-57d3-4acb-b982-fa923425e48a)

WIll be in next update today

**Comment by Frooodle** [comment]
just changed it so the example above will be 2  1 not 3  2 oops

**Comment by IngMFernandez** [comment]
Great! For now it works as intended. The only thing that could make it better is the possibility to make multiple operations in series/consequently/in batch: in this case it would be ordering the software to the split and then merge the output. Don't know if this is an issue already. Either way, I consider for now this matter closed. Hope I will be able to use this open source tool throughout the next year. With such an outstanding "customer service", I will be glad to try and help in a more material way when I get my stuff together. Cheers!

**Comment by Frooodle** [comment]
Defo many tickets raised and it is planned one day

**Comment by numboDumbo** [comment]
Hey, i don't think this work properly. I did a vertical split in a landscape pdf. The split wasn't happening from the middle of the page. I choose 1 vertical.
I tried rotating to pdf and then splitting horizontally. This resulted in a very skewered and whole page being shifted vertically with huge top margins. I choose 1 horizontal.

Am I doing something wrong?

**Comment by jzedwards** [comment]
Sorry for commenting on an old thread, but this looks like a great feature, but I cannot see how to find it in the app. Can I get a pointer to how to access and use (I scan a lot of double page booklets)
