### ISSUE TITLE
No message available for path: /updateUserSettings

### ISSUE THREAD

**Issue by alexdraconian** [Frooodle/Stirling-PDF#515]
I tried to sync my settings from browser to account, but encountered with 404 error "No message available for path: /updateUserSettings". This also happens when sync opposite direction.

  * Synology container manager environment. Mapped configs folder and tessdata.
  * Using login feature.
  * All other things are working fine, like account management, user settings, PDF functions...

**Comment by Frooodle** [comment]
in 0.17.0 !
