### ISSUE TITLE
[Feature request] Split PDF by size

### ISSUE THREAD

**Issue by Yusaney** [Frooodle/Stirling-PDF#518]
It would be awesome to have an option to split a PDF by a maximum size.

a parameter to pass the max size in MB example: 20.

Upload a 100MB file, resulting in a split of 5 files...

**Comment by Frooodle** [comment]
@Yusaney  added in alpha tag, will be in next release
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/406cde0b-8d00-4415-ac49-625e74fd40b8)

**Comment by Frooodle** [comment]
released in latest 0.17.0!
