### ISSUE TITLE
Missing Output Types

### ISSUE THREAD

**Issue by lilkideminem** [Frooodle/Stirling-PDF#52]
Missing JPG, GIF formats for PDF To Image. Was in previous version. Running Latest Update.
![S-PDF](https://user-images.githubusercontent.com/62624396/219516800-bf029c1b-c084-4caf-9383-aaaf27b08ca3.jpg)

**Comment by Frooodle** [comment]
When changing functionality to split images different and format colour and dpi I unfortunately lost a ability to produce a jpg directly.

If you require jpeg (or others) output then I can add a workaround for it next update

**Comment by lilkideminem** [comment]
I think having the options would be awesome but its your program.

**Comment by Frooodle** [comment]
Done for next release
