### ISSUE TITLE
accessibility issue

### ISSUE THREAD

**Issue by GloriaaaC** [Frooodle/Stirling-PDF#521]
Hi team,

Just wondering whether the accessibility tags added in the HTML file will be successfully converted and result in an accessible PDF when converting HTML to PDF?

I am using podman to run Stirling-pdf with the image frooodle/s-pdf:latest.

**Comment by Frooodle** [comment]
I doubt it sadly, but i cant say for certain. in background stirling-pdf uses 
https://weasyprint.org/
so would need ot check there
