### ISSUE TITLE
Error 504 when converting PDF to PPTX

### ISSUE THREAD

**Issue by fdecourt** [Frooodle/Stirling-PDF#530]
Hi,
On the v0.17.1 when converting PDF to PPTX, I have this error : 
![image](https://github.com/Frooodle/Stirling-PDF/assets/4050977/93002412-c27c-4996-b1f8-3a5fcdba8346)

Without anything in the log : 
Running command: soffice --infilter=impress_pdf_import --convert-to pptx --outdir /tmp/output_11510095656446401842 /tmp/input_5340029605811857543.pdf08:14:10.573 [http-nio-8080-exec-5] INFO  o.s.api.AbstractOpenApiResource - Init duration for springdoc-openapi is: 5490 ms

I am using it behing a NGINX proxy.

Thanks for your help

**Comment by Frooodle** [comment]
This normally means nginx timed out the request

What's your nginx config? Do you increase timeouts etc

**Comment by fdecourt** [comment]
Hi, 
You were right, it was a NGINX time out. Thanks for youyr help.
Regards,

**Comment by bigbeka** [comment]
Hi @fdecourt, I am using NGINX for reverse proxy too. Could you share your config you set to accommodate larger files?
