### ISSUE TITLE
(Sugestão) Notificação sobre uso de cookies

### ISSUE THREAD

**Issue by JefPresotto** [Frooodle/Stirling-PDF#544]
Olá,
Seria possível colocar o aviso sobre uso de cookies como na maioria dos sites ?
No brasil a Lei Geral de Proteção de Dados (LGPD) obrigada o uso da notificação. Por isso acho que seria bem interessante adicionar no Stirling, que está cada dia mais completo.

Abaixo uma imagem de exemplo de um site de noticias..

![cookies policy](https://github.com/Frooodle/Stirling-PDF/assets/48888772/6f5471ef-26cb-4f1c-9d82-4e901ba8ae1d)

**Comment by Frooodle** [comment]
This is not applicable for stirling-PDF
EU law states that only non-essensial cookies not vital to the websites functionality must require a prompt like the above.

This is for adverts, tracking, analytics etc.
In this case the only cookies Stirling-PDF use are session management for login etc
Also if there is no login enabled i dont believe any cookies are used within stirling-pdf anyway

**Comment by JefPresotto** [comment]
Entendi, mas obrigado novamente pelo feedback.
