### ISSUE TITLE
[Bug] SPDF on Unraid needs log path, otherwise crash

### ISSUE THREAD

**Issue by TBT-TBT** [Frooodle/Stirling-PDF#556]
The Unraid app standard Stirling PDF configuration does not include the 

`      - /location/of/logs:/logs/`

path. This lets it crash (and switch off) with the error:

`
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[AUTHLOG] - Failed to create parent directories for [/logs/invalid-auths.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[AUTHLOG] - openFile(logs/invalid-auths.log,true) call failed. java.io.FileNotFoundException: logs/invalid-auths.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[GENERAL] - Failed to create parent directories for [/logs/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[GENERAL] - openFile(logs/info.log,true) call failed. java.io.FileNotFoundException: logs/info.log (No such file or directory)
`

Creating a folder at
"/mnt/user/appdata/Stirling-PDF/logs/"

and configuring a new Path, with "Container Path" /logs, "Host Path" /mnt/user/appdata/Stirling-PDF/logs/ and "Access Mode "Read/Write" will solve this problem and let SPDF run again.

**Comment by Frooodle** [comment]
Thanks for this, i will update docker app to pre-create logs folder to avoid its access issue.. it should fix the need for logs mount
