### ISSUE TITLE
Convert file to pdf fails

### ISSUE THREAD

**Issue by manuelkamp** [Frooodle/Stirling-PDF#575]
Error
Internal Server Error:Command process failed with exit code 1. Error message: /usr/local/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives from distutils.version import LooseVersion unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice ERROR: No module named 'base' unoconv: Cannot find a suitable office installation on your system. ERROR: Please locate your office installation and send your feedback to: http://github.com/dagwieers/unoconv/issues

**Comment by Frooodle** [comment]
Docker or local?

**Comment by manuelkamp** [comment]
local on Ubuntu 22.04 with everything installed as per documentation

**Comment by manuelkamp** [comment]
So the issue is, that on Ubuntu 22.04 the default Python version is 3.10 - Stirling-PDF obviously needs 3.8, which is not mentioned in the documentation (only Python 3 is mentioned as requirement).

Solution is:
apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
apt install python3.8-distutils

wget https://bootstrap.pypa.io/get-pip.py
python3.8 get-pip.py
python3.8 -m pip install --upgrade pip

ls /usr/bin/python*
sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.10 1
sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.8 2
sudo update-alternatives --config python

python3 --version
pip3 --version

**Comment by Frooodle** [comment]
Reopening so I remember to update docs :)

**Comment by matthiasmett** [comment]
I tried the solution but get the same error message. I run Stirling-PDF local on Ubuntu 22.04.

After trying the steps, the versions are:

python3 --version
Python 3.10.12

pip3 --version
pip 24.0 from /home/administrator/.local/lib/python3.10/site-packages/pip (python 3.10)
