### ISSUE TITLE
Feature request: OCR

### ISSUE THREAD

**Issue by mrnetlex** [Frooodle/Stirling-PDF#58]
Firstly - thanks for this neat project, I was looking for exactly something like this few days ago.

Would it possible to add OCR as one of the tools? There's a good working CLI tool called [OCRmyPDF](https://github.com/ocrmypdf/OCRmyPDF) so maybe it wouldn't be too hard to implement.

**Comment by Frooodle** [comment]
Maybe.... Ill take a look, generally, a lot of OCR is very bulky and i have had people request to keep filesize down.
Long term I will take a look at it though

**Comment by mrnetlex** [comment]
To be fair, I didn't think about file size, because for me its far more important to be able to search my PDF with CTRL+F, but of course no pressure, just an idea

**Comment by Frooodle** [comment]
I mean filesize of the app itself 

Regardless I been trying this out
Got the OCR itself working but having issues adding it back to PDF in a nice way
Not sure how best to go about it
What's the result from a app like the one you mentioned ? 
Do you have a example file you can share too?

**Comment by Frooodle** [comment]
Sorry looking at this some more and tested that OCRmyPDF
I can do the OCR and get the string but inputting it back into the document with the format etc perfectly is not something i have the knowledge on and OCRmyPDF does a much better job

**Comment by Frooodle** [comment]
Will keep ticket open but no plans to do this myself currently

**Comment by Frooodle** [comment]
Added this feature, decided to use OCRMyPDF directly as its so good

**Comment by mrnetlex** [comment]
Sorry, for not being active. 
I'm glad that you have been able to use OCRmyPDF and add OCR functionality. Thanks 👍
