### ISSUE TITLE
translation missing for "Search"

### ISSUE THREAD

**Issue by manuelkamp** [Frooodle/Stirling-PDF#583]
If you click top right on the search-icon, the pre-filled text in the textbox is always "Search", regardless of the selected language.
<img width="181" alt="Screenshot 2023-12-27 200926" src="https://github.com/Frooodle/Stirling-PDF/assets/48356947/1b1feccb-a07d-4b69-b679-8cf3d78d7b90">

**Comment by sbplat** [comment]
Fixed in the latest release.
