### ISSUE TITLE
Feature Request: Mirroring

### ISSUE THREAD

**Issue by 7flash** [Frooodle/Stirling-PDF#592]
Feature

Allow mirror pdf page like da Vinci's handwriting.

Example

<img width="171" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/4569866/a22bf54d-d2c1-48f5-a2cd-4635c7c154eb">

Purpose

Exercise right-brain thinking while reading this way

**Comment by Frooodle** [comment]
Sorry no plans for this
