### ISSUE TITLE
add rotate pages feature

### ISSUE THREAD

**Issue by Chuchodavids** [Frooodle/Stirling-PDF#6]

**Comment by Frooodle** [comment]
Sure!

**Comment by Frooodle** [comment]
I plan to update the overall UI for this later but this okay for now?

![image](https://user-images.githubusercontent.com/77850077/215335616-bd6cc6cd-4712-463d-a7de-e5dfb047ef15.png)
![image](https://user-images.githubusercontent.com/77850077/215335621-cb9abb24-9371-48fb-8004-293edad0a872.png)

**Comment by Frooodle** [comment]
Added in https://github.com/Frooodle/Stirling-PDF/pull/7

**Comment by truthsword** [comment]
Yes... but not in limited to 90 degree multiples, but to any degree (including decimals... 5.7 degrees, for example).

Thank you!
