### ISSUE TITLE
`Back to Main Page` Button is glitech

### ISSUE THREAD

**Issue by DenuxPlays** [Frooodle/Stirling-PDF#603]
# Screenshot:

![image](https://github.com/Frooodle/Stirling-PDF/assets/83671398/25006a02-6fe2-41e2-82e9-78923c5c7763)

Whole site:

![image](https://github.com/Frooodle/Stirling-PDF/assets/83671398/afbb4089-1019-418c-bc78-7be6681e9de7)

You can reproduce it when using the `View PDF` feature

**Comment by Frooodle** [comment]
Known bug, issue already raised, looking into it
