### ISSUE TITLE
APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by iball** [Frooodle/Stirling-PDF#609]
Was working just until I pulled down the latest updated container.

> 
stirling-pdf  | 
stirling-pdf  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
stirling-pdf  | 01:13:59.325 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 
stirling-pdf  | 
stirling-pdf  | ***************************
stirling-pdf  | APPLICATION FAILED TO START
stirling-pdf  | ***************************
stirling-pdf  | 
stirling-pdf  | Description:
stirling-pdf  | 
stirling-pdf  | Field userService in stirling.software.SPDF.controller.api.pipeline.PipelineProcessor required a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' that could not be found.
stirling-pdf  | 
stirling-pdf  | The injection point has the following annotations:
stirling-pdf  |         - @org.springframework.beans.factory.annotation.Autowired(required=true)
stirling-pdf  | 
stirling-pdf  | 
stirling-pdf  | Action:
stirling-pdf  | 
stirling-pdf  | Consider defining a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' in your configuration.
stirling-pdf  | 
stirling-pdf  | Copying original files without overwriting existing files
stirling-pdf  | Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.18.0
stirling-pdf  | Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
stirling-pdf  |  ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____ 
stirling-pdf  | / ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
stirling-pdf  | \___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_   
stirling-pdf  |  ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|  
stirling-pdf  | |____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|                                                                 
stirling-pdf  | Powered by Spring Boot 3.1.2
stirling-pdf  | 01:14:01.653 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.18.0 using Java 17.0.9 with PID 1 (/app.jar started by root in /)
stirling-pdf  | 01:14:01.655 [main] INFO  s.software.SPDF.SPdfApplication - No active profile set, falling back to 1 default profile: "default"
stirling-pdf  | 01:14:03.235 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
stirling-pdf  | 01:14:03.243 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
stirling-pdf  | 01:14:03.245 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
stirling-pdf  | 01:14:03.245 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.11]
stirling-pdf  | 01:14:03.332 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
stirling-pdf  | 01:14:03.333 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1594 ms
stirling-pdf  | 01:14:03.583 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelineProcessor': Unsatisfied dependency expressed through field 'userService': No qualifying bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
stirling-pdf  | 01:14:03.587 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
stirling-pdf  | 01:14:03.608 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLogger - 
stirling-pdf  | 
stirling-pdf  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
stirling-pdf  | 01:14:03.628 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 
stirling-pdf  | 
stirling-pdf  | ***************************
stirling-pdf  | APPLICATION FAILED TO START
stirling-pdf  | ***************************
stirling-pdf  | 
stirling-pdf  | Description:
stirling-pdf  | 
stirling-pdf  | Field userService in stirling.software.SPDF.controller.api.pipeline.PipelineProcessor required a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' that could not be found.
stirling-pdf  | 
stirling-pdf  | The injection point has the following annotations:
stirling-pdf  |         - @org.springframework.beans.factory.annotation.Autowired(required=true)
stirling-pdf  | 
stirling-pdf  | 
stirling-pdf  | Action:
stirling-pdf  | 
stirling-pdf  | Consider defining a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' in your configuration.
stirling-pdf  | 
stirling-pdf  | Copying original files without overwriting existing files
stirling-pdf  | Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.18.0
stirling-pdf  | Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
stirling-pdf  |  ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____ 
stirling-pdf  | / ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
stirling-pdf  | \___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_   
stirling-pdf  |  ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|  
stirling-pdf  | |____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|                                                                 
stirling-pdf  | Powered by Spring Boot 3.1.2
stirling-pdf  | 01:14:06.691 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.18.0 using Java 17.0.9 with PID 1 (/app.jar started by root in /)
stirling-pdf  | 01:14:06.693 [main] INFO  s.software.SPDF.SPdfApplication - No active profile set, falling back to 1 default profile: "default"
stirling-pdf  | 01:14:08.200 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
stirling-pdf  | 01:14:08.210 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
stirling-pdf  | 01:14:08.212 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
stirling-pdf  | 01:14:08.213 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.11]
stirling-pdf  | 01:14:08.283 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
stirling-pdf  | 01:14:08.284 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1536 ms
stirling-pdf  | 01:14:08.559 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelineProcessor': Unsatisfied dependency expressed through field 'userService': No qualifying bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
stirling-pdf  | 01:14:08.562 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
stirling-pdf  | 01:14:08.581 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLogger - 
stirling-pdf  | 
stirling-pdf  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
stirling-pdf  | 01:14:08.600 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 
stirling-pdf  | 
stirling-pdf  | ***************************
stirling-pdf  | APPLICATION FAILED TO START
stirling-pdf  | ***************************
stirling-pdf  | 
stirling-pdf  | Description:
stirling-pdf  | 
stirling-pdf  | Field userService in stirling.software.SPDF.controller.api.pipeline.PipelineProcessor required a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' that could not be found.
stirling-pdf  | 
stirling-pdf  | The injection point has the following annotations:
stirling-pdf  |         - @org.springframework.beans.factory.annotation.Autowired(required=true)
stirling-pdf  | 
stirling-pdf  | 
stirling-pdf  | Action:
stirling-pdf  | 
stirling-pdf  | Consider defining a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' in your configuration.
stirling-pdf  |

**Comment by banjuer** [comment]
+1

**Comment by huyang19881115** [comment]
2023-12-30 01:52:37,304 INFO s.s.S.SPdfApplication [main] Starting SPdfApplication v0.18.0 using Java 17.0.9 with PID 1 (/app.jar started by root in /)
2023-12-30 01:52:37,306 INFO s.s.S.SPdfApplication [main] No active profile set, falling back to 1 default profile: "default"
2023-12-30 01:52:38,235 INFO o.s.b.w.e.t.TomcatWebServer [main] Tomcat initialized with port(s): 8080 (http)
2023-12-30 01:52:38,241 INFO o.a.c.h.Http11NioProtocol [main] Initializing ProtocolHandler ["http-nio-8080"]
2023-12-30 01:52:38,242 INFO o.a.c.c.StandardService [main] Starting service [Tomcat]
2023-12-30 01:52:38,243 INFO o.a.c.c.StandardEngine [main] Starting Servlet engine: [Apache Tomcat/10.1.11]
2023-12-30 01:52:38,293 INFO o.a.c.c.C.[.[.[/] [main] Initializing Spring embedded WebApplicationContext
2023-12-30 01:52:38,294 INFO o.s.b.w.s.c.ServletWebServerApplicationContext [main] Root WebApplicationContext: initialization completed in 951 ms
2023-12-30 01:52:38,433 WARN o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelineProcessor': Unsatisfied dependency expressed through field 'userService': No qualifying bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2023-12-30 01:52:38,435 INFO o.a.c.c.StandardService [main] Stopping service [Tomcat]
2023-12-30 01:52:38,448 INFO o.s.b.a.l.ConditionEvaluationReportLogger [main] 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-30 01:52:38,461 ERROR o.s.b.d.LoggingFailureAnalysisReporter [main] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userService in stirling.software.SPDF.controller.api.pipeline.PipelineProcessor required a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' in your configuration.

2023-12-30 01:56:50,289 INFO s.s.S.SPdfApplication [main] Starting SPdfApplication v0.18.0 using Java 17.0.9 with PID 1 (/app.jar started by root in /)
2023-12-30 01:56:50,290 INFO s.s.S.SPdfApplication [main] No active profile set, falling back to 1 default profile: "default"
2023-12-30 01:56:51,189 INFO o.s.b.w.e.t.TomcatWebServer [main] Tomcat initialized with port(s): 8080 (http)
2023-12-30 01:56:51,196 INFO o.a.c.h.Http11NioProtocol [main] Initializing ProtocolHandler ["http-nio-8080"]
2023-12-30 01:56:51,198 INFO o.a.c.c.StandardService [main] Starting service [Tomcat]
2023-12-30 01:56:51,198 INFO o.a.c.c.StandardEngine [main] Starting Servlet engine: [Apache Tomcat/10.1.11]
2023-12-30 01:56:51,265 INFO o.a.c.c.C.[.[.[/] [main] Initializing Spring embedded WebApplicationContext
2023-12-30 01:56:51,266 INFO o.s.b.w.s.c.ServletWebServerApplicationContext [main] Root WebApplicationContext: initialization completed in 945 ms
2023-12-30 01:56:51,420 WARN o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelineProcessor': Unsatisfied dependency expressed through field 'userService': No qualifying bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2023-12-30 01:56:51,422 INFO o.a.c.c.StandardService [main] Stopping service [Tomcat]
2023-12-30 01:56:51,434 INFO o.s.b.a.l.ConditionEvaluationReportLogger [main] 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-30 01:56:51,446 ERROR o.s.b.d.LoggingFailureAnalysisReporter [main] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userService in stirling.software.SPDF.controller.api.pipeline.PipelineProcessor required a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'stirling.software.SPDF.controller.api.pipeline.UserServiceInterface' in your configuration.

一样的docker 启动就报错，不知道是什么问题导致的，感觉是配置文件缺少导致的吧

**Comment by Frooodle** [comment]
Sorry I see what issue is
Will have to resolve this tomorrow morning 
In meantime you can either run with docker security as true 

Or run older tag

**Comment by Frooodle** [comment]
latest image is rebuilding now should be up in 2 mins

**Comment by Frooodle** [comment]
Please try now!

**Comment by trentnbauer** [comment]
the container started for me but I don't have the time to test anything just yet
![image](https://github.com/Frooodle/Stirling-PDF/assets/45578026/1dc146e5-d1b2-46c2-b476-ab759761a858)

![image](https://github.com/Frooodle/Stirling-PDF/assets/45578026/18f1f538-e021-49e8-9a80-0f1f8c5d2632)

**Comment by banjuer** [comment]
> Please try now! @iball @banjuer @huyang19881115 please let me know

fixed thanks :)

**Comment by MartinEngelbrecht** [comment]
I have the same problem. Deleted the entire container, image and config folder. Had to change the security option to true and then recreate. Now it works.

**Comment by Frooodle** [comment]
@MartinEngelbrecht you should be able to just. Pull 0.18.1 image now with no other issues

**Comment by huyang19881115** [comment]
thanks，start success，just set security ＝true



---- Replied Message ----
| From | Anthony ***@***.***> |
| Date | 12/30/2023 17:21 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Frooodle/Stirling-PDF] APPLICATION FAILED TO START (Issue #609) |

@MartinEngelbrecht you should be able to just. Pull 0.18.1 image now with no other issues

**Comment by wolkenschieber** [comment]
> @MartinEngelbrecht you should be able to just. Pull 0.18.1 image now with no other issues

FYI, I still needed to set
```yaml
    environment:
      SECURITY: true
```
with tag _0.18.1_.

**Comment by Frooodle** [comment]
@wolkenschieber  What error do you get without that set? And can you confirm the version on the settings page on website?

**Comment by wolkenschieber** [comment]
Sorry my bad: I must have done something wrong during trouble shooting. I can confirm that the Striling-PDF image with tag _0.18.1_ is running fine without additional setttings:
```
✔ Container stirling-pdf  Created                                                                                                                                                                                                                                                                                     0.0s 
Attaching to stirling-pdf
stirling-pdf  | Copying original files without overwriting existing files
stirling-pdf  | Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.18.1
stirling-pdf  | Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
stirling-pdf  |  ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____ 
stirling-pdf  | / ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
stirling-pdf  | \___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_   
stirling-pdf  |  ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|  
stirling-pdf  | |____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|                                                                 
stirling-pdf  | Powered by Spring Boot 3.1.2
stirling-pdf  | 17:34:32.299 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.18.1 using Java 17.0.9 with PID 1 (/app.jar started by root in /)

```
