### ISSUE TITLE
Feature request: Image extraction from PDFs

### ISSUE THREAD

**Issue by Samurai1201** [Frooodle/Stirling-PDF#65]
First of all, thanks for your work on this excellent project.

For my workflow a feature to extract the pictures embedded in a pdf would be really helpful. Because I need this feature somewhat often I still have to use a desktop pdf editor.

Thanks in advance

**Comment by Frooodle** [comment]
Sounds like a good feature
I'll look into adding it this weekend if all goes well

**Comment by Frooodle** [comment]
Got the feature working today, it only extracts images fully labelled as an image in the PDF.
I can try scraping it further but ill release it as is tomorrow. Please try it tomorrow and let me know if it meets your expectations!

**Comment by Frooodle** [comment]
As an example of the current workflow this PDF generates this zip of images
[E13271_PRIME_Z370-A_UM_WEB.pdf](https://github.com/Frooodle/Stirling-PDF/files/10866128/E13271_PRIME_Z370-A_UM_WEB.pdf)
[E13271_PRIME_Z370-A_UM_WEB_extracted-images (1).zip](https://github.com/Frooodle/Stirling-PDF/files/10866131/E13271_PRIME_Z370-A_UM_WEB_extracted-images.1.zip)

**Comment by Samurai1201** [comment]
Thanks, works perfectly for me. Only a progress indicator would be helpful for large files

**Comment by Frooodle** [comment]
Sadly due to how process works a progress bar etc wouldn't be possible 

I'll add a loading or spinning orb or something to better show it waiting though 
Good feedback

**Comment by Frooodle** [comment]
I take it back, it might be possible, ill look into it
