### ISSUE TITLE
Copy Stack Trace does not work without Showing Stack Trace first

### ISSUE THREAD

**Issue by shomilsaini** [Frooodle/Stirling-PDF#68]
![image](https://user-images.githubusercontent.com/46788173/223754256-e5c7efef-f126-4819-8b88-82dbb53ce2c5.png)

Copy Stack Trace buton copies nothing if you do not click show stack trace first.
IMO it should still copy even if I dont want to see on screen. especially an issue on mobile browsers.

![image](https://user-images.githubusercontent.com/46788173/223755670-784e26fa-a2cf-46a8-8d3a-ba20d8ae817e.png)

**Comment by Frooodle** [comment]
Will fix for next release, thanks for pointing this out
