### ISSUE TITLE
Feature Request: Crop PDF

### ISSUE THREAD

**Issue by Frooodle** [Frooodle/Stirling-PDF#71]

**Comment by tvmp** [comment]
I'd like to second this please. Ideally, a visual crop, but also a numerical crop (say top bottom left right in mm) would be great!

**Comment by Frooodle** [comment]
Not the only one to request this 
I'll ask you as well

Does it mater for this usecase if it gets converted to a image first
Resized and then back to pdf?
Downside is text would not be selectable anymore 

I can't think of any other way to "crop" a PDF

**Comment by gen2fish** [comment]
For my use-case losing the text is fine, as I'm mostly doing sheet music.

**Comment by Frooodle** [comment]
Done in V0.11.0
