### ISSUE TITLE
There is a typo in the new image to pdf implementation

### ISSUE THREAD

**Issue by jordyjordy** [Frooodle/Stirling-PDF#78]
The field for selecting images has a wrong label/placeholder

**Expected behaviour:**
The field says "Select Image(s)"

**Actual behaviour:**
The field says "Select PDF(s)"

**How to reproduce:**
Visit the page for the image converter, read the label.

**Comment by Frooodle** [comment]
Fixed as part of https://github.com/Frooodle/Stirling-PDF/issues/78
Will be included in next release

Thankyou for the input!
