### ISSUE TITLE
Feature Request: pdf to .xls, .doc (Update: Done for .doc, .xls still remaining)

### ISSUE THREAD

**Issue by jufy111** [Frooodle/Stirling-PDF#89]
Hey mate, thanks for this project, it is probably the single most useful docker image out there.

Have you considered adding functionality to convert pdfs to word (.doc) and excel (.xls) file types.

**Comment by Frooodle** [comment]
Lemme get this added for next release :)

**Comment by Frooodle** [comment]
Done for doc and docx and few others
just released now
couldnt get xls working this weekend so will have to work on that later

**Comment by Frooodle** [comment]
Sorry XLS conversion is a bit to complex 
I am going to drop this feature at least for now

**Comment by Tediore** [comment]
It would be amazing if you were able to add PDF to XLS conversion at some point!
